'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Data.SqlClient

Public Class Customer

    Public Const CustomerTableConstant As String = "Customer"

    Private m_CUSTOMERID As Integer = -1

    Private m_CUSTOMERDEL As Boolean = False

    Private m_COMID As String = String.Empty

    Private m_CUSTOMERCD As String = String.Empty

    Private m_CUSTOMERNAME As String = String.Empty

    Private m_DISTRIBCD As String = String.Empty

    Private m_CADD1 As String = String.Empty

    Private m_CADD2 As String = String.Empty

    Private m_CMCONT As String = String.Empty

    Private m_CMPHON As String = String.Empty

    Private m_VAT As Boolean = False

    Private m_CDACD As String = String.Empty

    Private m_ZIPCD As String = String.Empty

    Private m_REGCD As String = String.Empty

    Private m_DISTCD As String = String.Empty

    Private m_AREACD As String = String.Empty

    Private m_TERRCD As String = String.Empty

    Private m_CMGRP As String = String.Empty

    Private m_CMCLASS As String = String.Empty

    Private m_AREACOVRG As String = String.Empty

    Private m_ACCNTSHRD As String = String.Empty

    Private m_CRTDDTE As Date = "1/1/1900"

    Private m_CRTDBY As String = String.Empty

    Private m_EffectivityStartDate As Date = "1/1/1900"

    Private m_EffectivityEndDate As Date = "1/1/1900"

    Private m_IsActive As Boolean = False

    Private m_PhReg As String = String.Empty

    Private m_Coodinator As String = String.Empty

    Private m_Discount As String = String.Empty

    Private m_ProponentCode As String = String.Empty

    Private m_PronentShipTo As String = String.Empty

    Private m_PioneerCode As String = String.Empty

    Private m_OAPEnrollement As Boolean = False

    Private m_OAPMemberShip As Boolean = False

    Private m_Remarks As String = String.Empty

    Public ReadOnly Property CUSTOMERID() As Integer
        Get
            Return m_CUSTOMERID
        End Get
    End Property

    Public Property CUSTOMERDEL() As Boolean
        Get
            Return m_CUSTOMERDEL
        End Get
        Set(ByVal value As Boolean)
            m_CUSTOMERDEL = value
        End Set
    End Property

    Public Property COMID() As String
        Get
            Return m_COMID
        End Get
        Set(ByVal value As String)
            m_COMID = value
        End Set
    End Property

    Public Property CUSTOMERCD() As String
        Get
            Return m_CUSTOMERCD
        End Get
        Set(ByVal value As String)
            m_CUSTOMERCD = value
        End Set
    End Property

    Public Property CUSTOMERNAME() As String
        Get
            Return m_CUSTOMERNAME
        End Get
        Set(ByVal value As String)
            m_CUSTOMERNAME = value
        End Set
    End Property

    Public Property DISTRIBCD() As String
        Get
            Return m_DISTRIBCD
        End Get
        Set(ByVal value As String)
            m_DISTRIBCD = value
        End Set
    End Property

    Public Property CADD1() As String
        Get
            Return m_CADD1
        End Get
        Set(ByVal value As String)
            m_CADD1 = value
        End Set
    End Property

    Public Property CADD2() As String
        Get
            Return m_CADD2
        End Get
        Set(ByVal value As String)
            m_CADD2 = value
        End Set
    End Property

    Public Property CMCONT() As String
        Get
            Return m_CMCONT
        End Get
        Set(ByVal value As String)
            m_CMCONT = value
        End Set
    End Property

    Public Property CMPHON() As String
        Get
            Return m_CMPHON
        End Get
        Set(ByVal value As String)
            m_CMPHON = value
        End Set
    End Property

    Public Property VAT() As Boolean
        Get
            Return m_VAT
        End Get
        Set(ByVal value As Boolean)
            m_VAT = value
        End Set
    End Property

    Public Property CDACD() As String
        Get
            Return m_CDACD
        End Get
        Set(ByVal value As String)
            m_CDACD = value
        End Set
    End Property

    Public Property ZIPCD() As String
        Get
            Return m_ZIPCD
        End Get
        Set(ByVal value As String)
            m_ZIPCD = value
        End Set
    End Property

    Public Property REGCD() As String
        Get
            Return m_REGCD
        End Get
        Set(ByVal value As String)
            m_REGCD = value
        End Set
    End Property

    Public Property DISTCD() As String
        Get
            Return m_DISTCD
        End Get
        Set(ByVal value As String)
            m_DISTCD = value
        End Set
    End Property

    Public Property AREACD() As String
        Get
            Return m_AREACD
        End Get
        Set(ByVal value As String)
            m_AREACD = value
        End Set
    End Property

    Public Property TERRCD() As String
        Get
            Return m_TERRCD
        End Get
        Set(ByVal value As String)
            m_TERRCD = value
        End Set
    End Property

    Public Property CMGRP() As String
        Get
            Return m_CMGRP
        End Get
        Set(ByVal value As String)
            m_CMGRP = value
        End Set
    End Property

    Public Property CMCLASS() As String
        Get
            Return m_CMCLASS
        End Get
        Set(ByVal value As String)
            m_CMCLASS = value
        End Set
    End Property

    Public Property AREACOVRG() As String
        Get
            Return m_AREACOVRG
        End Get
        Set(ByVal value As String)
            m_AREACOVRG = value
        End Set
    End Property

    Public Property ACCNTSHRD() As String
        Get
            Return m_ACCNTSHRD
        End Get
        Set(ByVal value As String)
            m_ACCNTSHRD = value
        End Set
    End Property

    Public Property CRTDDTE() As Date
        Get
            Return m_CRTDDTE
        End Get
        Set(ByVal value As Date)
            m_CRTDDTE = value
        End Set
    End Property

    Public Property CRTDBY() As String
        Get
            Return m_CRTDBY
        End Get
        Set(ByVal value As String)
            m_CRTDBY = value
        End Set
    End Property

    Public Property EffectivityStartDate() As Date
        Get
            Return m_EffectivityStartDate
        End Get
        Set(ByVal value As Date)
            m_EffectivityStartDate = value
        End Set
    End Property

    Public Property EffectivityEndDate() As Date
        Get
            Return m_EffectivityEndDate
        End Get
        Set(ByVal value As Date)
            m_EffectivityEndDate = value
        End Set
    End Property

    Public Property IsActive() As Boolean
        Get
            Return m_IsActive
        End Get
        Set(ByVal value As Boolean)
            m_IsActive = value
        End Set
    End Property
    Public Property PHReg() As String
        Get
            Return m_PhReg
        End Get
        Set(ByVal value As String)
            m_PhReg = value
        End Set
    End Property
    Public Property Coordinator As String
        Get
            Return m_Coodinator
        End Get
        Set(value As String)
            m_Coodinator = value
        End Set
    End Property
    Public Property Discount As String
        Get
            Return m_Discount
        End Get
        Set(value As String)
            m_Discount = value
        End Set
    End Property
    Public Property ProponentCode As String
        Get
            Return m_ProponentCode
        End Get
        Set(value As String)
            m_ProponentCode = value
        End Set
    End Property
    Public Property ProponentShipto As String
        Get
            Return m_PronentShipTo
        End Get
        Set(value As String)
            m_PronentShipTo = value
        End Set
    End Property
    Public Property PioneerCode As String
        Get
            Return m_PioneerCode
        End Get
        Set(value As String)
            m_PioneerCode = value
        End Set
    End Property
    Public Property OAPEnrollemnt As Boolean
        Get
            Return m_OAPEnrollement
        End Get
        Set(value As Boolean)
            m_OAPEnrollement = value
        End Set
    End Property
    Public Property OAPMemberShip As Boolean
        Get
            Return m_OAPMemberShip
        End Get
        Set(value As Boolean)
            m_OAPMemberShip = value
        End Set
    End Property
    Public Property Remarks As String
        Get
            Return m_Remarks
        End Get
        Set(value As String)
            m_Remarks = value
        End Set
    End Property

    Public Function Update() As Boolean
        If SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Closed Or SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Broken Then SPMSOPCI.ConnectionModule.Connect()
        Try
            Dim cmd As New SqlCommand("uspCustomer", SPMSOPCI.ConnectionModule.SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "UPDATE")
            cmd.Parameters.AddWithValue("@CUSTOMERDEL", m_CUSTOMERDEL)
            cmd.Parameters.AddWithValue("@COMID", m_COMID)
            cmd.Parameters.AddWithValue("@CUSTOMERCD", m_CUSTOMERCD)
            cmd.Parameters.AddWithValue("@CUSTOMERNAME", m_CUSTOMERNAME)
            cmd.Parameters.AddWithValue("@DISTRIBCD", m_DISTRIBCD)
            cmd.Parameters.AddWithValue("@CADD1", m_CADD1)
            cmd.Parameters.AddWithValue("@CADD2", m_CADD2)
            cmd.Parameters.AddWithValue("@CMCONT", m_CMCONT)
            cmd.Parameters.AddWithValue("@CMPHON", m_CMPHON)
            cmd.Parameters.AddWithValue("@VAT", m_VAT)
            cmd.Parameters.AddWithValue("@CDACD", m_CDACD)
            cmd.Parameters.AddWithValue("@ZIPCD", m_ZIPCD)
            cmd.Parameters.AddWithValue("@REGCD", m_REGCD)
            cmd.Parameters.AddWithValue("@DISTCD", m_DISTCD)
            cmd.Parameters.AddWithValue("@AREACD", m_AREACD)
            cmd.Parameters.AddWithValue("@TERRCD", m_TERRCD)
            cmd.Parameters.AddWithValue("@CMGRP", m_CMGRP)
            cmd.Parameters.AddWithValue("@CMCLASS", m_CMCLASS)
            cmd.Parameters.AddWithValue("@AREACOVRG", m_AREACOVRG)
            If m_ACCNTSHRD = "N" Then
                cmd.Parameters.AddWithValue("@ACCNTSHRD", False)
            Else
                cmd.Parameters.AddWithValue("@ACCNTSHRD", True)
            End If

            cmd.Parameters.AddWithValue("@CRTDDTE", m_CRTDDTE)
            cmd.Parameters.AddWithValue("@CRTDBY", m_CRTDBY)
            cmd.Parameters.AddWithValue("@EffectivityStartDate", m_EffectivityStartDate)
            cmd.Parameters.AddWithValue("@EffectivityEndDate", m_EffectivityEndDate)
            cmd.Parameters.AddWithValue("@IsActive", m_IsActive)
            cmd.Parameters.AddWithValue("@PHREGCD", m_PhReg)
            cmd.Parameters.AddWithValue("@ProponetCode", m_ProponentCode)
            cmd.Parameters.AddWithValue("@ProponentShipto", m_PronentShipTo)
            cmd.Parameters.AddWithValue("@PioneerCode", m_PioneerCode)
            cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
            m_CUSTOMERID = cmd.ExecuteScalar()
            SPMSOPCI.ConnectionModule.Disconnect()
            Return True

        Catch ex As Exception
            SPMSOPCI.ConnectionModule.Disconnect()
            Throw
        End Try

    End Function


    Public Function Save() As Boolean
        If SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Closed Or SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Broken Then SPMSOPCI.ConnectionModule.Connect()
        Try
            Dim cmd As New SqlCommand("uspNewCustomer", SPMSOPCI.ConnectionModule.SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "SAVE")
            cmd.Parameters.AddWithValue("@CustomerID", m_CUSTOMERID)
            cmd.Parameters.AddWithValue("@CUSTOMERDEL", False)
            cmd.Parameters.AddWithValue("@COMID", m_COMID)
            cmd.Parameters.AddWithValue("@CUSTOMERCD", m_CUSTOMERCD)
            cmd.Parameters.AddWithValue("@CUSTOMERNAME", m_CUSTOMERNAME)
            cmd.Parameters.AddWithValue("@CADD1", m_CADD1)
            cmd.Parameters.AddWithValue("@CADD2", m_CADD2)
            cmd.Parameters.AddWithValue("@CMCONT", m_CMCONT)
            cmd.Parameters.AddWithValue("@CMPHON", m_CMPHON)
            cmd.Parameters.AddWithValue("@VAT", m_VAT)
            cmd.Parameters.AddWithValue("@ACCNTSHRD", m_ACCNTSHRD)
            cmd.Parameters.AddWithValue("@CDACD", m_CDACD)
            cmd.Parameters.AddWithValue("@ZIPCD", m_ZIPCD)
            cmd.Parameters.AddWithValue("@REGCD", m_REGCD)
            cmd.Parameters.AddWithValue("@DISTCD", m_DISTCD)
            cmd.Parameters.AddWithValue("@AREACD", m_AREACD)
            cmd.Parameters.AddWithValue("@CMGRP", m_CMGRP)
            cmd.Parameters.AddWithValue("@CMCLASS", m_CMCLASS)
            cmd.Parameters.AddWithValue("@CRTDBY", m_CRTDBY)
            cmd.Parameters.AddWithValue("@EffectivityStartDate", m_EffectivityStartDate)
            cmd.Parameters.AddWithValue("@EffectivityEndDate", m_EffectivityEndDate)
            cmd.Parameters.AddWithValue("@ISACTIVE", True)
            cmd.Parameters.AddWithValue("@DISCOUNT", m_Discount)
            cmd.Parameters.AddWithValue("@Coordinator", m_Coodinator)
            cmd.Parameters.AddWithValue("@ProponetCode", m_ProponentCode)
            cmd.Parameters.AddWithValue("@ProponentShipto", m_PronentShipTo)
            cmd.Parameters.AddWithValue("@PioneerCode", m_PioneerCode)
            cmd.Parameters.AddWithValue("@OAPEnrollement", m_OAPEnrollement)
            cmd.Parameters.AddWithValue("@OAPMemberShip", m_OAPMemberShip)
            cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
            m_CUSTOMERID = cmd.ExecuteScalar
            SPMSOPCI.ConnectionModule.Disconnect()
            Return True
        Catch ex As System.Exception
            SPMSOPCI.ConnectionModule.Disconnect()
            Throw
        End Try
    End Function

    Public Function Delete() As Boolean
        If SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Closed Or SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Broken Then SPMSOPCI.ConnectionModule.Connect()
        Try
            Dim cmd As New SqlCommand("uspCustomer", SPMSOPCI.ConnectionModule.SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Delete")
            cmd.Parameters.AddWithValue("@CUSTOMERID", m_CUSTOMERID)
            cmd.ExecuteNonQuery()
            SPMSOPCI.ConnectionModule.Disconnect()
            Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function

    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As CustomerCollection
        Dim col As New CustomerCollection
        For j As Integer = 0 To table.Rows.Count - 1
            Dim m_Customer As New Customer
            Dim row As DataRow = table.Rows(j)
            m_Customer.m_CUSTOMERID = row("CUSTOMERSHIPTOID")
            m_Customer.m_CUSTOMERDEL = row("CustomerShiptodel")
            m_Customer.m_COMID = row("COMID")
            m_Customer.m_CUSTOMERCD = row("CUSTOMERCD")
            m_Customer.m_CUSTOMERNAME = row("CDANAME")
            m_Customer.m_DISTRIBCD = row("COMID")
            m_Customer.m_CADD1 = row("CDACADD1")
            m_Customer.m_CADD2 = row("CDACADD2")
            m_Customer.m_CMCONT = row("CDACONT")
            m_Customer.m_CMPHON = row("CDAPHON")
            m_Customer.m_VAT = row("VAT")
            m_Customer.m_CDACD = row("CDACD")
            m_Customer.m_ZIPCD = row("ZIPCD")
            m_Customer.m_REGCD = row("REGCD")
            m_Customer.m_DISTCD = row("DISTCD")
            m_Customer.m_AREACD = row("AREACD")
            m_Customer.m_TERRCD = row("TERRCD")
            m_Customer.m_CMGRP = row("CMGRP")
            m_Customer.m_CMCLASS = row("CMCLASS")
            m_Customer.m_AREACOVRG = row("AREACOVRG")
            m_Customer.m_ACCNTSHRD = row("ACCNTSHRD")
            m_Customer.m_CRTDDTE = row("CRTDDTE")
            m_Customer.m_CRTDBY = row("CRTDBY")
            m_Customer.m_EffectivityStartDate = row("EffectivityStartDate")
            m_Customer.m_EffectivityEndDate = row("EffectivityEndDate")
            m_Customer.m_IsActive = row("IsActive")
            m_Customer.m_Coodinator = row("Coordinator")
            m_Customer.m_Discount = row("Discount")
            m_Customer.m_ProponentCode = row("ProponetCode")
            m_Customer.m_PronentShipTo = row("ProponentShipTo")
            m_Customer.m_PioneerCode = row("PioneerCode")
            m_Customer.m_OAPEnrollement = row("OAPEnrollement")
            m_Customer.m_OAPMemberShip = row("OAPMemberShip")
            m_Customer.m_Remarks = row("Remarks")
            col.Add(m_Customer)
        Next
        Return col
    End Function

    Public Shared Function Filter(ByVal Condition As String) As CustomerCollection
        Return BaseFilter(GetRecords("SELECT * FROM CustomerShipto  WHERE  CustomerShiptodel = 0 AND " & IIf(Condition <> "", Condition, "")))
    End Function

    Public Overloads Shared Function Load() As CustomerCollection
        Return Filter("")
    End Function

    Public Overloads Shared Function Load(ByVal CUSTOMERID As Integer) As Customer
        Return Filter("CUSTOMERSHIPTOID = " & CUSTOMERID)(0)
    End Function

    Public Shared Function LoadByCode(ByVal CustomerCode As String) As Customer
        Return Filter("CUSTOMERCD = '" & RefineSQL(CustomerCode) & "'")(0)
    End Function

    Public Shared Function LoadByName(ByVal CustomerName As String) As Customer
        Return Filter("CustomerName = '" & RefineSQL(CustomerName) & "'")(0)
    End Function

    Public Shared Function GetCustomerNameByCode(ByVal CustomerCode As String) As String
        Return LoadByCode(CustomerCode).CUSTOMERNAME
    End Function

    Public Shared Function GetCustomerGroupByCustomerCode(ByVal CustomerCode As String) As String
        Return LoadByCode(CustomerCode).CMGRP
    End Function

    Public Shared Function GetCustomerCodeByName(ByVal CustomerName As String) As String
        Return LoadByName(CustomerName).CUSTOMERCD
    End Function

    Public Shared Function GetCustomerSql(Optional ByVal CustomerGroup As String = "") As String
        Return "SELECT CUSTOMERID, CUSTOMERCD, CUSTOMERCD , CustomerName, CADD1 + ' ' + CADD2 [Address] FROM Customer Where CUSTOMERDEL = 0 " & IIf(CustomerGroup <> "", " AND CMGRP = '" & CustomerGroup & "'", "")
    End Function

    Public Shared Function GetCustomerColumns() As String
        Return "CUSTOMERID; CustomerCD; CustomerName;"
    End Function

    Public Shared Function CheckCustomerIfExist(ByVal CustomerCode As String) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM Customer  WHERE  CustomerDEL = 0 AND CustomerCD ='" & CustomerCode & "'") = "A"
    End Function

    Public Shared Function CheckCustomerAndCompanyIfExist(ByVal CustomerCode As String, ByVal ID As Integer) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM Customer  WHERE  CustomerDEL = 0 AND CustomerCD ='" & RefineSQL(CustomerCode) & "' AND CUSTOMERID <> " & ID) = "A"
    End Function
    Public Shared Function CheckCustomerAndCompanyIfExist1(ByVal CustomerCode As String, ByVal CustomerShipToCode As String, ByVal CompanyCode As String, ByVal ID As Integer) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM CustomerShipto  WHERE  CustomerShiptodel = 0 AND CustomerCD ='" & RefineSQL(CustomerCode) & "' AND CDACD = '" & CustomerShipToCode & "'AND COMID = '" & CompanyCode & "' AND CUSTOMERSHIPTOID <> " & ID) = "A"
    End Function
    Public Shared Function DeleteExistCustomer(ByVal CustomerCode As String) As Boolean
        Return ExecuteCommand("DELETE Customer  WHERE  CustomerDEL = 0 AND CustomerCD ='" & CustomerCode & "'")
    End Function
    Public Shared Function CustomerFindlist(ByVal ChannelCode As String) As String
        Return "SELECT CUSTOMERSHIPTOID,COMID [Distributor Code], CUSTOMERCD [Customer Code],CDACD [Customer ShipTo], CDANAME [Customer Name], CDACADD1 + ' ' + CDACADD2 [Address] FROM CustomerShipto Where COMID  = '" & ChannelCode & "' Order by CUSTOMERCD,CDACD"
    End Function
    Public Shared Function GetCustomerProponent(ByVal ChannelCode As String) As String
        Return "SELECT CUSTOMERSHIPTOID, CUSTOMERCD [Customer Code], CDANAME [Customer Name],CDACD [Shipto Code] ,CDACADD1 + ' ' + CDACADD2 [Address] FROM CustomerShipto Where COMID  = '" & ChannelCode & "'"
    End Function
    Public Shared Function GetCustomerPoineer(ByVal ChannelCode As String) As String
        Return "SELECT CUSTOMERSHIPTOID, CUSTOMERCD [Customer Code], CDANAME [Customer Name],CDACD [Shipto Code] ,CDACADD1 + ' ' + CDACADD2 [Address] FROM CustomerShipto Where COMID  = '" & ChannelCode & "'"
    End Function
    Public Shared Function GetCustomerProponentSelected(ByVal CompanyCode As String, ByVal Code As String) As String
        Return "SELECT CUSTOMERID, CUSTOMERCD, CUSTOMERCD , CustomerName, CADD1 + ' ' + CADD2 [Address] FROM Customer Where COMID  = '" & CompanyCode & "' And CUSTOMERCD = '" & Code & "'"
    End Function
    Public Shared Function GetProponentSql(ByVal Code As String, ByVal Shipto As String) As String
        Return "SELECT ID,Code,Name,Shipto From [Proponent] Where DLTFLG = 0 And Code = '" & Code & "' And Shipto = '" & Shipto & "'"
    End Function
    Public Shared Function GetPioneerSql(ByVal Code As String, ByVal Shipto As String) As String
        Return "SELECT ID,Code,Name,Shipto From [Pioneer] Where DLTFLG = 0 And Code = '" & Code & "' And Shipto = '" & Shipto & "'"
    End Function
    Public Shared Function CheckProponent(ByVal CompanyCode As String, ByVal Code As String, ByVal ShipTo As String) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM CustomerShipTo   Where COMID = '" & CompanyCode & "' AND CUSTOMERCD ='" & Code & "' And CDACD = '" & ShipTo & "'") = "A"
    End Function
    Public Shared Function CheckPioneer(ByVal CompanyCode As String, ByVal Code As String, ByVal ShipTo As String) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM CustomerShipTo   Where COMID = '" & CompanyCode & "' AND CUSTOMERCD ='" & Code & "' And CDACD = '" & ShipTo & "'") = "A"
    End Function
End Class
Public Class CustomerCollection

    Inherits List(Of Customer)
End Class

