'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data
Imports System.Data.SqlClient

Public Class CustomerShipTo

    Public Const CustomerShipToTableConstant As String = "CustomerShipTo"

    Private m_CUSTOMERSHIPTOID As Integer = -1

    Private m_CUSTOMERSHIPTODEL As Boolean = False

    Private m_CUSTOMERCD As String = String.Empty

    Private m_CDACD As String = String.Empty

    Private m_CDANAME As String = String.Empty

    Private m_CDACADD1 As String = String.Empty

    Private m_CDACADD2 As String = String.Empty

    Private m_CDACONT As String = String.Empty

    Private m_CDAPHON As String = String.Empty

    Private m_ZIPCD As String = String.Empty

    Private m_REGCD As String = String.Empty

    Private m_DISTCD As String = String.Empty

    Private m_AREACD As String = String.Empty

    Private m_TERRCD As String = String.Empty

    Private m_CMGRP As String = String.Empty

    Private m_CMCLASS As String = String.Empty

    Private m_AREACOVRG As String = String.Empty

    Private m_ACCNTSHRD As String = String.Empty

    Private m_CRTDDTE As Date = "1/1/1900"

    Private m_CRTDBY As String = String.Empty

    Private m_COMID As String = String.Empty

    Private m_EffectivityStartDate As Date = "1/1/1900"

    Private m_EffectivityEndDate As Date = "1/1/1900"

    Private m_IsActive As Boolean = False

    Private m_PHREGCD As String = String.Empty

    Private m_Coordinator As String = String.Empty

    Private m_ProponentCode As String = String.Empty

    Private m_ProponentShipto As String = String.Empty

    Private m_PioneerCode As String = String.Empty

    Private m_CustomerShiptoIDD As Integer = -1

    Private m_OAPEnrollement As Boolean = False

    Private m_OAPMemberShip As Boolean = False

    Private m_Remarks As String = String.Empty

    Private m_Discount As String = String.Empty

    Private m_VAT As Boolean = False

    Private m_CustomerofType As Integer = 0

    Private m_MunTax As String = "0"

    Private m_DistMargin As String = "0"

    Private m_IsActiveVat As Boolean = False

    Public ReadOnly Property CUSTOMERSHIPTOID() As Integer
        Get
            Return m_CUSTOMERSHIPTOID
        End Get
    End Property

    Public Property CustomerShiptoIDD As Integer
        Get
            Return m_CustomerShiptoIDD
        End Get
        Set(value As Integer)
            m_CustomerShiptoIDD = value
        End Set
    End Property
    Public Property CUSTOMERSHIPTODEL() As Boolean
        Get
            Return m_CUSTOMERSHIPTODEL
        End Get
        Set(ByVal value As Boolean)
            m_CUSTOMERSHIPTODEL = value
        End Set
    End Property

    Public Property CUSTOMERCD() As String
        Get
            Return m_CUSTOMERCD
        End Get
        Set(ByVal value As String)
            m_CUSTOMERCD = value
        End Set
    End Property

    Public Property CDACD() As String
        Get
            Return m_CDACD
        End Get
        Set(ByVal value As String)
            m_CDACD = value
        End Set
    End Property

    Public Property CDANAME() As String
        Get
            Return m_CDANAME
        End Get
        Set(ByVal value As String)
            m_CDANAME = value
        End Set
    End Property

    Public Property CDACADD1() As String
        Get
            Return m_CDACADD1
        End Get
        Set(ByVal value As String)
            m_CDACADD1 = value
        End Set
    End Property

    Public Property CDACADD2() As String
        Get
            Return m_CDACADD2
        End Get
        Set(ByVal value As String)
            m_CDACADD2 = value
        End Set
    End Property

    Public Property CDACONT() As String
        Get
            Return m_CDACONT
        End Get
        Set(ByVal value As String)
            m_CDACONT = value
        End Set
    End Property

    Public Property CDAPHON() As String
        Get
            Return m_CDAPHON
        End Get
        Set(ByVal value As String)
            m_CDAPHON = value
        End Set
    End Property

    Public Property ZIPCD() As String
        Get
            Return m_ZIPCD
        End Get
        Set(ByVal value As String)
            m_ZIPCD = value
        End Set
    End Property

    Public Property REGCD() As String
        Get
            Return m_REGCD
        End Get
        Set(ByVal value As String)
            m_REGCD = value
        End Set
    End Property

    Public Property DISTCD() As String
        Get
            Return m_DISTCD
        End Get
        Set(ByVal value As String)
            m_DISTCD = value
        End Set
    End Property

    Public Property AREACD() As String
        Get
            Return m_AREACD
        End Get
        Set(ByVal value As String)
            m_AREACD = value
        End Set
    End Property

    Public Property TERRCD() As String
        Get
            Return m_TERRCD
        End Get
        Set(ByVal value As String)
            m_TERRCD = value
        End Set
    End Property

    Public Property CMGRP() As String
        Get
            Return m_CMGRP
        End Get
        Set(ByVal value As String)
            m_CMGRP = value
        End Set
    End Property

    Public Property CMCLASS() As String
        Get
            Return m_CMCLASS
        End Get
        Set(ByVal value As String)
            m_CMCLASS = value
        End Set
    End Property

    Public Property AREACOVRG() As String
        Get
            Return m_AREACOVRG
        End Get
        Set(ByVal value As String)
            m_AREACOVRG = value
        End Set
    End Property

    Public Property ACCNTSHRD() As String
        Get
            Return m_ACCNTSHRD
        End Get
        Set(ByVal value As String)
            m_ACCNTSHRD = value
        End Set
    End Property

    Public Property CRTDDTE() As Date
        Get
            Return m_CRTDDTE
        End Get
        Set(ByVal value As Date)
            m_CRTDDTE = value
        End Set
    End Property

    Public Property CRTDBY() As String
        Get
            Return m_CRTDBY
        End Get
        Set(ByVal value As String)
            m_CRTDBY = value
        End Set
    End Property

    Public Property COMID() As String
        Get
            Return m_COMID
        End Get
        Set(ByVal value As String)
            m_COMID = value
        End Set
    End Property

    Public Property EffectivityStartDate() As Date
        Get
            Return m_EffectivityStartDate
        End Get
        Set(ByVal value As Date)
            m_EffectivityStartDate = value
        End Set
    End Property

    Public Property EffectivityEndDate() As Date
        Get
            Return m_EffectivityEndDate
        End Get
        Set(ByVal value As Date)
            m_EffectivityEndDate = value
        End Set
    End Property

    Public Property IsActive() As Boolean
        Get
            Return m_IsActive
        End Get
        Set(ByVal value As Boolean)
            m_IsActive = value
        End Set
    End Property
    Public Property PHREGCD() As String
        Get
            Return m_PHREGCD
        End Get
        Set(ByVal value As String)
            m_PHREGCD = value
        End Set
    End Property
    Public Property Coordinator As String
        Get
            Return m_Coordinator
        End Get
        Set(value As String)
            m_Coordinator = value
        End Set
    End Property
    Public Property ProponentCode As String
        Get
            Return m_ProponentCode
        End Get
        Set(value As String)
            m_ProponentCode = value
        End Set
    End Property
    Public Property ProponentShipto As String
        Get
            Return m_ProponentShipto
        End Get
        Set(value As String)
            m_ProponentShipto = value
        End Set
    End Property
    Public Property PioneerCode As String
        Get
            Return m_PioneerCode
        End Get
        Set(value As String)
            m_PioneerCode = value
        End Set
    End Property
    Public Property OAPEnrollment As Boolean
        Get
            Return m_OAPEnrollement
        End Get
        Set(value As Boolean)
            m_OAPEnrollement = value
        End Set
    End Property
    Public Property OAPMemberShip As Boolean
        Get
            Return m_OAPMemberShip
        End Get
        Set(value As Boolean)
            m_OAPMemberShip = value
        End Set
    End Property
    Public Property Remarks As String
        Get
            Return m_Remarks
        End Get
        Set(value As String)
            m_Remarks = value
        End Set
    End Property
    Public Property Discount As String
        Get
            Return m_Discount
        End Get
        Set(value As String)
            m_Discount = value
        End Set
    End Property
    Public Property VAT As Boolean
        Get
            Return m_VAT
        End Get
        Set(value As Boolean)
            m_VAT = value
        End Set
    End Property
    Public Property CustomerofType As Integer
        Get
            Return m_CustomerofType
        End Get
        Set(value As Integer)
            m_CustomerofType = value
        End Set
    End Property
    Public Property MunTax As String
        Get
            Return m_MunTax
        End Get
        Set(value As String)
            m_MunTax = value
        End Set
    End Property
    Public Property DistMargin As String
        Get
            Return m_DistMargin
        End Get
        Set(value As String)
            m_DistMargin = value
        End Set
    End Property
    Public Property IsActiveVat As Boolean
        Get
            Return m_IsActiveVat
        End Get
        Set(value As Boolean)
            m_IsActiveVat = value
        End Set
    End Property
    Public Function CustomerShiptoSave() As Boolean
        If SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Closed Or SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Broken Then SPMSOPCI.ConnectionModule.Connect()
        Try
            Dim cmd As New SqlCommand("uspNewCustomerShipTo", SPMSOPCI.ConnectionModule.SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "SAVE")
            cmd.Parameters.AddWithValue("@CustomershipToID", m_CUSTOMERSHIPTOID)
            cmd.Parameters.AddWithValue("@CUSTOMERSHIPTODEL", m_CUSTOMERSHIPTODEL)
            cmd.Parameters.AddWithValue("@CUSTOMERCD", m_CUSTOMERCD)
            cmd.Parameters.AddWithValue("@CDACD", m_CDACD)
            cmd.Parameters.AddWithValue("@CDANAME", m_CDANAME)
            cmd.Parameters.AddWithValue("@CDACADD1", m_CDACADD1)
            cmd.Parameters.AddWithValue("@CDACADD2", m_CDACADD2)
            cmd.Parameters.AddWithValue("@CDACONT", m_CDACONT)
            cmd.Parameters.AddWithValue("@CDAPHON", m_CDAPHON)
            cmd.Parameters.AddWithValue("@ZIPCD", m_ZIPCD)
            cmd.Parameters.AddWithValue("@REGCD", m_REGCD)
            cmd.Parameters.AddWithValue("@DISTCD", m_DISTCD)
            cmd.Parameters.AddWithValue("@AREACD", m_AREACD)
            cmd.Parameters.AddWithValue("@CMGRP", m_CMGRP)
            cmd.Parameters.AddWithValue("@CMCLASS", m_CMCLASS)
            cmd.Parameters.AddWithValue("@ACCNTSHRD", m_ACCNTSHRD)
            cmd.Parameters.AddWithValue("@CRTDDTE", m_CRTDDTE)
            cmd.Parameters.AddWithValue("@CRTDBY", m_CRTDBY)
            cmd.Parameters.AddWithValue("@COMID", m_COMID)
            cmd.Parameters.AddWithValue("@EffectivityStartDate", m_EffectivityStartDate)
            cmd.Parameters.AddWithValue("@EffectivityEndDate", m_EffectivityEndDate)
            cmd.Parameters.AddWithValue("@IsActive", m_IsActive)
            cmd.Parameters.AddWithValue("@Coordinator", m_Coordinator)
            cmd.Parameters.AddWithValue("@ProponentCode", m_ProponentCode)
            cmd.Parameters.AddWithValue("@ProponentShipto", m_ProponentShipto)
            cmd.Parameters.AddWithValue("@PioneerCode", m_PioneerCode)
            cmd.Parameters.AddWithValue("@OAPEnrollement", m_OAPEnrollement)
            cmd.Parameters.AddWithValue("@OAPMemberShip", m_OAPMemberShip)
            cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
            cmd.Parameters.AddWithValue("@MunTax", m_MunTax)
            cmd.Parameters.AddWithValue("@DistMargin", m_DistMargin)
            cmd.Parameters.AddWithValue("@ISACTIVEVAT", m_IsActiveVat)
            m_CUSTOMERSHIPTOID = cmd.ExecuteScalar()
            SPMSOPCI.ConnectionModule.Disconnect()
            Return True
        Catch ex As System.Exception
            SPMSOPCI.ConnectionModule.Disconnect()
            Throw
        End Try
    End Function
    Public Function UpdateCustomerShipTo() As Boolean
        If SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Closed Or SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Broken Then SPMSOPCI.ConnectionModule.Connect()
        Try
            Dim cmd As New SqlCommand("uspNewCustomerShipTo", SPMSOPCI.ConnectionModule.SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "UPDATE")
            cmd.Parameters.AddWithValue("@CUSTOMERSHIPTODEL", m_CUSTOMERSHIPTODEL)
            cmd.Parameters.AddWithValue("@CUSTOMERCD", m_CUSTOMERCD)
            cmd.Parameters.AddWithValue("@CDACD", m_CDACD)
            cmd.Parameters.AddWithValue("@CDANAME", m_CDANAME)
            cmd.Parameters.AddWithValue("@CDACADD1", m_CDACADD1)
            cmd.Parameters.AddWithValue("@CDACADD2", m_CDACADD2)
            cmd.Parameters.AddWithValue("@CDACONT", m_CDACONT)
            cmd.Parameters.AddWithValue("@CDAPHON", m_CDAPHON)
            cmd.Parameters.AddWithValue("@ZIPCD", m_ZIPCD)
            cmd.Parameters.AddWithValue("@REGCD", m_REGCD)
            cmd.Parameters.AddWithValue("@DISTCD", m_DISTCD)
            cmd.Parameters.AddWithValue("@AREACD", m_AREACD)
            cmd.Parameters.AddWithValue("@CMGRP", m_CMGRP)
            cmd.Parameters.AddWithValue("@CMCLASS", m_CMCLASS)
            cmd.Parameters.AddWithValue("@ACCNTSHRD", m_ACCNTSHRD)
            cmd.Parameters.AddWithValue("@CRTDDTE", m_CRTDDTE)
            cmd.Parameters.AddWithValue("@CRTDBY", m_CRTDBY)
            cmd.Parameters.AddWithValue("@COMID", m_COMID)
            cmd.Parameters.AddWithValue("@EffectivityStartDate", m_EffectivityStartDate)
            cmd.Parameters.AddWithValue("@EffectivityEndDate", m_EffectivityEndDate)
            cmd.Parameters.AddWithValue("@IsActive", m_IsActive)
            cmd.Parameters.AddWithValue("@Coordinator", m_Coordinator)
            cmd.Parameters.AddWithValue("@ProponentCode", m_ProponentCode)
            cmd.Parameters.AddWithValue("@ProponentShipto", m_ProponentShipto)
            cmd.Parameters.AddWithValue("@PioneerCode", m_PioneerCode)
            cmd.Parameters.AddWithValue("@OAPEnrollement", m_OAPEnrollement)
            cmd.Parameters.AddWithValue("@OAPMemberShip", m_OAPMemberShip)
            cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
            cmd.Parameters.AddWithValue("@MunTax", m_MunTax)
            cmd.Parameters.AddWithValue("@DistMargin", m_DistMargin)
            cmd.Parameters.AddWithValue("@ISACTIVEVAT", m_IsActiveVat)
            cmd.ExecuteNonQuery()
            SPMSOPCI.ConnectionModule.Disconnect()
            Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function
   
    Public Function Delete() As Boolean
        If SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Closed Or SPMSOPCI.ConnectionModule.SPMSConn2.State = ConnectionState.Broken Then SPMSOPCI.ConnectionModule.Connect()
        Try
            Dim cmd As New SqlCommand("uspCustomerShipTo", SPMSOPCI.ConnectionModule.SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Delete")
            cmd.Parameters.AddWithValue("@CUSTOMERSHIPTOID", m_CUSTOMERSHIPTOID)
            cmd.ExecuteNonQuery()
            SPMSOPCI.ConnectionModule.Disconnect()
            Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function

    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As CustomerShipToCollection
        Dim col As New CustomerShipToCollection
        For j As Integer = 0 To table.Rows.Count - 1
            Dim m_CustomerShipTo As New CustomerShipTo
            Dim row As DataRow = table.Rows(j)
            m_CustomerShipTo.m_CUSTOMERSHIPTOID = row("CUSTOMERSHIPTOID")
            m_CustomerShipTo.m_CUSTOMERSHIPTODEL = row("CUSTOMERSHIPTODEL")
            m_CustomerShipTo.m_CUSTOMERCD = row("CUSTOMERCD")
            m_CustomerShipTo.m_CDACD = row("CDACD")
            m_CustomerShipTo.m_CDANAME = row("CDANAME")
            m_CustomerShipTo.m_CDACADD1 = row("CDACADD1")
            m_CustomerShipTo.m_CDACADD2 = row("CDACADD2")
            m_CustomerShipTo.m_CDACONT = row("CDACONT")
            m_CustomerShipTo.m_CDAPHON = row("CDAPHON")
            m_CustomerShipTo.m_ZIPCD = row("ZIPCD")
            m_CustomerShipTo.m_REGCD = row("REGCD")
            m_CustomerShipTo.m_DISTCD = row("DISTCD")
            m_CustomerShipTo.m_AREACD = row("AREACD")
            m_CustomerShipTo.m_TERRCD = row("TERRCD")
            m_CustomerShipTo.m_CMGRP = row("CMGRP")
            m_CustomerShipTo.m_CMCLASS = row("CMCLASS")
            m_CustomerShipTo.m_AREACOVRG = row("AREACOVRG")
            m_CustomerShipTo.m_ACCNTSHRD = row("ACCNTSHRD")
            m_CustomerShipTo.m_CRTDDTE = row("CRTDDTE")
            m_CustomerShipTo.m_CRTDBY = row("CRTDBY")
            m_CustomerShipTo.m_COMID = row("COMID")
            m_CustomerShipTo.m_EffectivityStartDate = row("EffectivityStartDate")
            m_CustomerShipTo.m_EffectivityEndDate = row("EffectivityEndDate")
            m_CustomerShipTo.m_IsActive = row("IsActive")
            m_CustomerShipTo.m_Coordinator = row("Coordinator")
            m_CustomerShipTo.m_ProponentCode = row("ProponetCode")
            m_CustomerShipTo.m_PioneerCode = row("PioneerCode")
            m_CustomerShipTo.m_ProponentShipto = row("ProponentShipTo")
            m_CustomerShipTo.m_OAPEnrollement = row("OAPEnrollement")
            m_CustomerShipTo.m_OAPMemberShip = row("OAPMemberShip")
            m_CustomerShipTo.m_Remarks = row("Remarks")
            m_CustomerShipTo.m_MunTax = row("MunTax")
            m_CustomerShipTo.m_DistMargin = row("DistMargin")
            m_CustomerShipTo.IsActiveVat = row("IsActiveVat")
            col.Add(m_CustomerShipTo)
        Next
        Return col
    End Function

    Public Shared Function Filter(ByVal Condition As String) As CustomerShipToCollection
        Return BaseFilter(GetRecords("SELECT * FROM CustomerShipTo  WHERE  CustomerShipToDel = 0 AND " & IIf(Condition <> "", Condition, "")))
    End Function

    Public Overloads Shared Function Load() As CustomerShipToCollection
        Return Filter("")
    End Function
    Public Shared Function LoadbyCode(ByVal CustomerCode As String) As CustomerShipTo
        Return Filter("CUSTOMERCD = '" & CustomerCode & "'")(0)
    End Function
    Public Overloads Shared Function Load(ByVal CustomerShipToID As Integer) As CustomerShipTo
        Return Filter("CustomerShipToID = " & CustomerShipToID)(0)
    End Function
    Public Shared Function CheckCustomerAndCompanyIfExist1(ByVal CustomerCode As String, ByVal CustomerShipToCode As String, ByVal CompanyCode As String, ByVal ID As Integer) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM CustomerShipto  WHERE  CustomerShiptodel = 0 AND CustomerCD ='" & RefineSQL(CustomerCode) & "' AND CDACD = '" & CustomerShipToCode & "'AND COMID = '" & CompanyCode & "' AND CUSTOMERSHIPTOID <> " & ID) = "A"
    End Function
    Public Shared Function GetCustomerSql(Optional ByVal COMID As String = "") As String
        Return "Select CustomerShipToID, CUSTOMERCD, CDANAME, PHREGCD [Region], CDACADD1 + ' ' + CDACADD2 [Address] FROM CustomerShipTo Where CUSTOMERSHIPTODEL = 0" & IIf(COMID <> "", " AND COMID = '" & COMID & "'", "")
    End Function
    Public Shared Function CheckCustomerAndCompanyIfExist1(ByVal CustomerCode As String, ByVal CustomerShipToCode As String, ByVal CompanyCode As String) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM CustomerShipto  WHERE  CustomerShiptodel = 0 AND CustomerCD ='" & RefineSQL(CustomerCode) & "' AND CDACD = '" & CustomerShipToCode & "'AND COMID = '" & CompanyCode & "'") = "A"
    End Function
    Public Shared Function GetCustomerSqls() As String
        Return "Select COMID,CUSTOMERCD [Customer Code],CDANAME [Customer Name],CDACD [Customer ShipTo],CDACADD1 [Address 1],CDACADD2 [Address 2] From CustomerShipTo Where COMID NOT IN ('MDCR') And CDANAME <> '' order by COMID,CUSTOMERCD"
    End Function

    Public Shared Function GetBranchSql() As String
        Return "Select CUSTOMERCD,CUSTOMERCD [Branch Code],CDANAME [Branch Name],CDACADD1 [Branch Address 1],CDACADD2 [Branch Address 2] From CustomerShipTo Where COMID IN ('MDC') And CDANAME <> '' order by COMID,CUSTOMERCD"
    End Function
    Public Shared Function GetBranchCodeSql(ByVal BranchCode As String) As String
        Return "Select CUSTOMERCD,CUSTOMERCD [Branch Code],CDANAME [Branch Name],CDACADD1 [Branch Address 1],CDACADD2 [Branch Address 2] From CustomerShipTo Where COMID IN ('MDC') And CDANAME <> '' And CUSTOMERCD = '" & BranchCode & "' order by COMID,CUSTOMERCD"
    End Function
    Public Shared Function CustomerFindlist(ByVal ChannelCode As String) As String
        Return "SELECT CUSTOMERSHIPTOID,COMID [Distributor Code], CUSTOMERCD [Customer Code],CDACD [Customer ShipTo], CDANAME [Customer Name], CDACADD1 + ' ' + CDACADD2 [Address] FROM CustomerShipto Where COMID  = '" & ChannelCode & "' Order by CUSTOMERCD,CDACD"
    End Function
    Public Shared Function GetCustomerColumns() As String
        Return "CustomerShipToID; CUSTOMERCD; CDANAME; PHREGCD"
    End Function

    Public Shared Function CheckCustomerIfExist(ByVal CustomerCode As String) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM CustomerShipTo  WHERE  CustomerShipToDEL = 0 AND CustomerCD ='" & CustomerCode & "'") = "A"
    End Function
    Public Shared Function DeleteExistCustomer(ByVal CustomerCode As String) As Boolean
        Return ExecuteCommand("DELETE CustomerShipTo  WHERE  CustomerShipToDEL = 0 AND CustomerCD ='" & CustomerCode & "'")
    End Function
    Public Shared Function GetCustomerProponent(ByVal ChannelCode As String) As String
        Return "SELECT CUSTOMERSHIPTOID, CUSTOMERCD [Customer Code], CDANAME [Customer Name],CDACD [Shipto Code] ,CDACADD1 + ' ' + CDACADD2 [Address] FROM CustomerShipto Where COMID  = '" & ChannelCode & "'"
    End Function
    Public Shared Function GetCustomerPoineer(ByVal ChannelCode As String) As String
        Return "SELECT CUSTOMERSHIPTOID, CUSTOMERCD [Customer Code], CDANAME [Customer Name],CDACD [Shipto Code] ,CDACADD1 + ' ' + CDACADD2 [Address] FROM CustomerShipto Where COMID  = '" & ChannelCode & "'"
    End Function
    Public Shared Function CheckProponent(ByVal CompanyCode As String, ByVal Code As String, ByVal ShipTo As String) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM CustomerShipTo   Where COMID = '" & CompanyCode & "' AND CUSTOMERCD ='" & Code & "' And CDACD = '" & ShipTo & "'") = "A"
    End Function
    Public Shared Function GetMDPrescriptionCustomer() As String
        Return "Select A.CUSTOMERSHIPTOID,A.COMID [Channel Code],A.Customercd [Account Code],A.CDANAME [Account Name],A.CDACD [Shipto Code],B.CustomerGroupName [Customer Group] From CustomerShipTo A INNER JOIN CustomerGroup B ON A.CMGRP = B.CustomerGroupcd  Where A.CUSTOMERSHIPTODEL = 0 "
    End Function
    Public Shared Function GetMDPrescriptionCustomers(ByVal CustomerID As Integer) As String
        Return "Select A.Customercd,A.CDANAME,A.CDACD,A.CDACADD1,A.CDACADD2,R.REGNAME,D.DISTRCTNAME,M.AREANAME,CG.CustomerGroupName,A.COMID From CustomerShipTo A LEFT JOIN Region R ON A.REGCD = R.REGCD LEFT JOIN District D ON A.DISTCD = D.DISTRCTCD AND D.REGCD = R.REGCD LEFT JOIN Area M ON A.REGCD = M.REGCD AND D.DISTRCTCD = A.DISTCD AND A.AREACD = M.AREACD LEFT JOIN CustomerGroup CG ON A.CMGRP = CG.CustomerGroupcd  Where A.CUSTOMERSHIPTODEL = 0 AND A.CUSTOMERSHIPTOID  = '" & CustomerID & "'"
    End Function
    Public Shared Function GetMDPrescriptionCustomersbyMDID(ByVal MDID As Integer) As String
        Return "Select A.Customercd,A.CDANAME,A.CDACD,A.CDACADD1,A.CDACADD2,R.REGNAME,D.DISTRCTNAME,M.AREANAME,CG.CustomerGroupName,A.COMID From CustomerShipTo A LEFT JOIN Region R ON A.REGCD = R.REGCD LEFT JOIN District D ON A.DISTCD = D.DISTRCTCD AND D.REGCD = R.REGCD LEFT JOIN Area M ON A.REGCD = M.REGCD AND D.DISTRCTCD = A.DISTCD AND A.AREACD = M.AREACD LEFT JOIN CustomerGroup CG ON A.CMGRP = CG.CustomerGroupcd INNER JOIN [MDPrescritionAccount] MA ON A.CUSTOMERCD = MA.AccountCode AND A.CDACD = MA.ShiptoCode AND A.COMID = MA.ChannelCode Where A.CUSTOMERSHIPTODEL = 0 AND MA.MDID = '" & MDID & "'"
    End Function
End Class

Public Class CustomerShipToColumnList

    Public Const CUSTOMERSHIPTOIDFieldConstant As String = "CUSTOMERSHIPTOID"

    Public Const CUSTOMERSHIPTODELFieldConstant As String = "CUSTOMERSHIPTODEL"

    Public Const CUSTOMERCDFieldConstant As String = "CUSTOMERCD"

    Public Const CDACDFieldConstant As String = "CDACD"

    Public Const CDANAMEFieldConstant As String = "CDANAME"

    Public Const CDACADD1FieldConstant As String = "CDACADD1"

    Public Const CDACADD2FieldConstant As String = "CDACADD2"

    Public Const CDACONTFieldConstant As String = "CDACONT"

    Public Const CDAPHONFieldConstant As String = "CDAPHON"

    Public Const ZIPCDFieldConstant As String = "ZIPCD"

    Public Const REGCDFieldConstant As String = "REGCD"

    Public Const DISTCDFieldConstant As String = "DISTCD"

    Public Const AREACDFieldConstant As String = "AREACD"

    Public Const TERRCDFieldConstant As String = "TERRCD"

    Public Const CMGRPFieldConstant As String = "CMGRP"

    Public Const CMCLASSFieldConstant As String = "CMCLASS"

    Public Const AREACOVRGFieldConstant As String = "AREACOVRG"

    Public Const ACCNTSHRDFieldConstant As String = "ACCNTSHRD"

    Public Const CRTDDTEFieldConstant As String = "CRTDDTE"

    Public Const CRTDBYFieldConstant As String = "CRTDBY"

    Public Const COMIDFieldConstant As String = "COMID"

    Public Const EffectivityStartDateFieldConstant As String = "EffectivityStartDate"

    Public Const EffectivityEndDateFieldConstant As String = "EffectivityEndDate"

    Public Const IsActiveFieldConstant As String = "IsActive"

    Public Const PHREGCDFieldConstant As String = "PHREGCD"

End Class

Public Class CustomerShipToCollection

    Inherits List(Of CustomerShipTo)
End Class
