CREATE TABLE [HistoricalRawdata] (
	HistoricalRawDataID  [int] IDENTITY (1, 1) NOT NULL ,
	[RawDataID] [int] NOT NULL DEFAULT -1,
	[CompanyCode] [varchar] (10)  NOT NULL DEFAULT (''),
	[BranchCode] [varchar] (10)  NOT NULL DEFAULT (''),
	[BranchName] [varchar] (255)  NOT NULL  DEFAULT (''),
	[CustomerNumber] [varchar] (10)  NOT NULL DEFAULT (''),
	[CustomerName] [varchar] (255)  NOT NULL DEFAULT (''),
	[CustomerAddress1] [varchar] (255)  NOT NULL DEFAULT (''),
	[CustomerAddress2] [varchar] (255)  NOT NULL DEFAULT (''),
	[TransactionDate] [varchar] (8)  NOT NULL DEFAULT (''),
	[InvoiceNumber] [varchar] (10) NOT NULL  DEFAULT (''),
	[TransactionType] [varchar] (2) NOT NULL  DEFAULT (''),
	[ItemNumber] [varchar] (20) NOT NULL DEFAULT (''),
	[ItemDescription] [varchar] (255) NOT NULL DEFAULT (''),
	[WarehouseNumber] [varchar] (3) NOT NULL DEFAULT (''),
	[Class] [varchar] (3) NOT NULL DEFAULT (''),
	[QuantitySold] [int] NOT NULL DEFAULT ((-1)),
	[QuantityFree] [int] NOT NULL DEFAULT ((-1)),
	[GrossAmount] [money] NOT NULL DEFAULT (0),
	[LineDiscount] [money] NOT NULL DEFAULT (0),
	[ProductDiscount] [money] NOT NULL DEFAULT (0),
	[VatCode] [varchar] (1) NOT NULL DEFAULT (''),
	[Route] [varchar] (6) NOT NULL DEFAULT (''),
	[Taxes] [money] NOT NULL DEFAULT (0),
	[Freight] [money] NOT NULL DEFAULT (0),
	[Additional] [money] NOT NULL DEFAULT (0),
	[NetAmount] [money] NOT NULL DEFAULT (0),
	[UnitPrice] [money] NOT NULL DEFAULT (0),
	[InvoiceReferenceNumber] [int] NOT NULL DEFAULT ((-1)),
	[CMCode] [varchar] (3) NOT NULL DEFAULT (''),
	[SONumber] [int] NOT NULL DEFAULT ((-1)),
	[SODate] [int] NOT NULL DEFAULT ((-1)),
	[SOTerms] [varchar] (6) NOT NULL DEFAULT (''),
	[ExpiryDate] [int] NOT NULL DEFAULT ((-1)),
	[LotNumber] [varchar] (15) NOT NULL DEFAULT (''),
	[SalesmanNumber] [varchar] (3) NOT NULL DEFAULT (''),
	[SalesmanName] [varchar] (24) NOT NULL DEFAULT (''),
	[ShipToName] [varchar] (50) NOT NULL DEFAULT (''),
	[ShipToAddress1] [varchar] (50) NOT NULL DEFAULT (''),
	[ShipToAddress2] [varchar] (50) NOT NULL DEFAULT (''),
	[ZipCode] [varchar] (6) NOT NULL DEFAULT (''),
	[TerritoryNumber] [varchar] (3) NOT NULL DEFAULT (''),
	[Area] [varchar] (3) NOT NULL DEFAULT (''),
	[CustomerClass] [varchar] (3) NOT NULL DEFAULT (''),
	[ClassName] [varchar] (24) NOT NULL DEFAULT (''),
	[Principal] [varchar] (3) NOT NULL DEFAULT (''),
	[SubPrincipal] [varchar] (6) NOT NULL DEFAULT (''),
	[PrincipalDivisionCode] [varchar] (3) NOT NULL DEFAULT (''),
	[SalesWeek] [varchar] (1) NOT NULL DEFAULT (''),
	[CustomerDeliveryCode] [varchar] (3)  NOT NULL  DEFAULT (''),
	[ListPriceTaxInclude] [varchar] (9)  NOT NULL  DEFAULT (''),
	[ContractPrincipalApprovalNumber] [varchar] (15) NOT NULL DEFAULT (''),
	[OrderType] [varchar] (1)  NOT NULL  DEFAULT (''),
	[IsCode] [varchar] (255)  NOT NULL DEFAULT (''),
	[UploadDate] [DateTime] NOT NULL DEFAULT ('1/1/1900'),
	 PRIMARY KEY  CLUSTERED 
	(
		[HistoricalRawDataID]
	)  ON [PRIMARY] 
) ON [PRIMARY]
GO


