'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule

Public Class ItemCostingDetails
    
    Public Const ItemCostingDetailsTableConstant As String = "ItemCostingDetails"
    
    Private m_ItemCostingDetailID As Integer = -1
    
    Private m_ItemCostingID As Integer = -1
    
    Private m_ItemCode As String = String.Empty
    
    Private m_ChannelItemCode As String = String.Empty
    
    Private m_ItemCost As Double = 0
    
    Public ReadOnly Property ItemCostingDetailID() As Integer
        Get
            Return m_ItemCostingDetailID
        End Get
    End Property
    
    Public Property ItemCostingID() As Integer
        Get
            Return m_ItemCostingID
        End Get
        Set
            m_ItemCostingID = value
        End Set
    End Property
    
    Public Property ItemCode() As String
        Get
            Return m_ItemCode
        End Get
        Set
            m_ItemCode = value
        End Set
    End Property
    
    Public Property ChannelItemCode() As String
        Get
            Return m_ChannelItemCode
        End Get
        Set
            m_ChannelItemCode = value
        End Set
    End Property
    
    Public Property ItemCost() As Double
        Get
            Return m_ItemCost
        End Get
        Set
            m_ItemCost = value
        End Set
    End Property
    
    Public Function Save() As Boolean
        Connect()
        Try 

            Dim cmd As New SqlCommand("uspItemCostingDetails", SPMSConn2)
				cmd.CommandType = CommandType.StoredProcedure
				cmd.Parameters.AddWithValue("@Action", "Save")
				cmd.Parameters.AddWithValue("@ItemCostingDetailID", m_ItemCostingDetailID)
				cmd.Parameters.AddWithValue("@ItemCostingID", m_ItemCostingID)
				cmd.Parameters.AddWithValue("@ItemCode", m_ItemCode)
				cmd.Parameters.AddWithValue("@ChannelItemCode", m_ChannelItemCode)
				cmd.Parameters.AddWithValue("@ItemCost", m_ItemCost)
				m_ItemCostingDetailID = cmd.ExecuteScalar()
            Disconnect()
				Return True
        Catch ex As System.Exception
            Disconnect()
            Throw
        End Try
    End Function
    
    Public Function Delete() As Boolean
        Connect()
        Try 

            Dim cmd As New SqlCommand("uspItemCostingDetails", SPMSConn2)
				cmd.CommandType = CommandType.StoredProcedure
				cmd.Parameters.AddWithValue("@Action", "Delete")
				cmd.Parameters.AddWithValue("@ItemCostingDetailID", m_ItemCostingDetailID)
				cmd.ExecuteNonQuery()
            Disconnect()
				Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function
    
    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As ItemCostingDetailsCollection
        Dim col as New ItemCostingDetailsCollection
        For j As Integer = 0 To table.Rows.Count - 1
        	Dim m_ItemCostingDetails as New ItemCostingDetails
        	Dim row as DataRow = table.Rows(j)
				m_ItemCostingDetails.m_ItemCostingDetailID = row("ItemCostingDetailID")
				m_ItemCostingDetails.m_ItemCostingID = row("ItemCostingID")
				m_ItemCostingDetails.m_ItemCode = row("ItemCode")
				m_ItemCostingDetails.m_ChannelItemCode = row("ChannelItemCode")
				m_ItemCostingDetails.m_ItemCost = row("ItemCost")
				col.Add(m_ItemCostingDetails)
        Next
        Return col
    End Function
    
    Public Shared Function Filter(ByVal Condition As String) As ItemCostingDetailsCollection
        Return BaseFilter(GetRecords("SELECT * FROM ItemCostingDetails " & IIf(Condition <> "", " WHERE " & Condition, "")))
    End Function
    
    Public Overloads Shared Function Load() As ItemCostingDetailsCollection
			Return Filter("")
    End Function
    
    Public Overloads Shared Function Load(ByVal ItemCostingDetailID As Integer) As ItemCostingDetails
			Return Filter("ItemCostingDetailID = " & ItemCostingDetailID)(0)
    End Function

    Public Shared Function LoadByItemCostingID(ByVal ItemCostingID As Integer) As ItemCostingDetailsCollection
        Return Filter("ItemCostingID = " & ItemCostingID)
    End Function

End Class
Public Class ItemCostingDetailsCollection

    Inherits List(Of ItemCostingDetails)
End Class
