ALTER       PROCEDURE [dbo].[uspDISTRIBUTOR]
	@DLTFLG BIT = 0,
	@DISTRIBUTORID Int = -1,
	@DISTCOMID VARCHAR(20) = '',
	@DISTNAME VARCHAR(255) = '',
	@CUST VARCHAR(25) = '',
	@ADDR VARCHAR(255) = '',
	@CRTDATE DATETIME = '1/1/1900',
	@CRTU VARCHAR(50) = '',
	@UPDD DATETIME = '1/1/1900',
	@UPDU VARCHAR(50) = '',
	@ACTION VARCHAR(10) = '',
	@OLDCODE VARCHAR(20) = '',
	@EFFECTIVITYSTARTDATE DATETIME = '1/1/1900',
	@EFFECTIVITYENDDATE DATETIME = '1/1/1900',
	@ISACTIVE BIT = 1
AS
IF @ACTION = 'ADD' BEGIN
		INSERT INTO DISTRIBUTOR (DLTFLG, DISTCOMID, DISTNAME, CUST, ADDR, CRTDATE, CRTU, UPDD, UPDU, EFFECTIVITYSTARTDATE, EFFECTIVITYENDDATE, ISACTIVE)
		VALUES(@DLTFLG, @DISTCOMID, @DISTNAME, @CUST, @ADDR, GETDATE(), @CRTU, GETDATE(), @UPDU, @EFFECTIVITYSTARTDATE, @EFFECTIVITYENDDATE, @ISACTIVE)
	END ELSE IF @ACTION = 'UPDATE' BEGIN
		UPDATE [DISTRIBUTOR] SET
			DLTFLG = @DLTFLG,
			DISTCOMID = @DISTCOMID,
			DISTNAME = @DISTNAME,
			CUST = @CUST,
			ADDR = @ADDR,
			CRTDATE = CRTDATE,
			CRTU = CRTU,
			UPDD = GETDATE(),
			UPDU = @UPDU,
			EFFECTIVITYSTARTDATE = @EFFECTIVITYSTARTDATE, 
			EFFECTIVITYENDDATE = @EFFECTIVITYENDDATE,
			ISACTIVE = @ISACTIVE
		WHERE	DISTRIBUTORID= @DISTRIBUTORID
		AND	DLTFLG = 0

	END ELSE IF @ACTION = 'DELETE' BEGIN

			UPDATE Distributor SET
				DLTFLG = @DLTFLG
			WHERE DISTRIBUTORID = @DISTRIBUTORID

	END

GO


