-------------------------------------------------------------------------------------------------------
-- Generated By Althea Data Layer Generator Version 03022010. DO NOT REMOVE
-- Generated on 9/1/2012
------------------------------------------------------------------------------------------------------

Alter Procedure uspCustomerShipTo
	 @Action as Varchar(100) = '',
	 @CUSTOMERSHIPTOID AS INT = -1,
	 @CUSTOMERSHIPTODEL AS BIT = 0,
	 @CUSTOMERCD AS VARCHAR(20) = '',
	 @CDACD AS VARCHAR(20) = '',
	 @CDANAME AS VARCHAR(255) = '',
	 @CDACADD1 AS VARCHAR(255) = '',
	 @CDACADD2 AS VARCHAR(255) = '',
	 @CDACONT AS VARCHAR(20) = '',
	 @CDAPHON AS VARCHAR(20) = '',
	 @ZIPCD AS VARCHAR(20) = '',
	 @REGCD AS VARCHAR(20) = '',
	 @DISTCD AS VARCHAR(20) = '',
	 @AREACD AS VARCHAR(20) = '',
	 @TERRCD AS VARCHAR(20) = '',
	 @CMGRP AS VARCHAR(20) = '',
	 @CMCLASS AS VARCHAR(20) = '',
	 @AREACOVRG AS VARCHAR(20) = '',
	 @ACCNTSHRD AS BIT = 0,
	 @CRTDDTE AS DATETIME = '1/1/1900',
	 @CRTDBY AS VARCHAR(50) = '',
	 @COMID AS VARCHAR(25) = '',
	 @EffectivityStartDate AS DATETIME = '1/1/1900',
	 @EffectivityEndDate AS DATETIME = '1/1/1900',
	 @IsActive AS BIT = 0

AS
	IF @Action = 'Save' BEGIN

		IF @CUSTOMERSHIPTOID = -1 BEGIN

			INSERT INTO CustomerShipTo(CUSTOMERSHIPTODEL, CUSTOMERCD, CDACD, CDANAME, CDACADD1, 
				CDACADD2, CDACONT, CDAPHON, ZIPCD, REGCD, 
				DISTCD, AREACD, TERRCD, CMGRP, CMCLASS, 
				AREACOVRG, ACCNTSHRD, CRTDDTE, CRTDBY, COMID, 
				EffectivityStartDate, EffectivityEndDate, IsActive)
			VALUES(@CUSTOMERSHIPTODEL, @CUSTOMERCD, @CDACD, @CDANAME, @CDACADD1, 
				@CDACADD2, @CDACONT, @CDAPHON, @ZIPCD, @REGCD, 
				@DISTCD, @AREACD, @TERRCD, @CMGRP, @CMCLASS, 
				@AREACOVRG, @ACCNTSHRD, @CRTDDTE, @CRTDBY, @COMID, 
				@EffectivityStartDate, @EffectivityEndDate, @IsActive)
			SELECT @@IDENTITY

		END ELSE BEGIN

			UPDATE CustomerShipTo SET CUSTOMERSHIPTODEL = @CUSTOMERSHIPTODEL,
				CUSTOMERCD = @CUSTOMERCD,
				CDACD = @CDACD,
				CDANAME = @CDANAME,
				CDACADD1 = @CDACADD1,
				CDACADD2 = @CDACADD2,
				CDACONT = @CDACONT,
				CDAPHON = @CDAPHON,
				ZIPCD = @ZIPCD,
				REGCD = @REGCD,
				DISTCD = @DISTCD,
				AREACD = @AREACD,
				TERRCD = @TERRCD,
				CMGRP = @CMGRP,
				CMCLASS = @CMCLASS,
				AREACOVRG = @AREACOVRG,
				ACCNTSHRD = @ACCNTSHRD,
				CRTDDTE = @CRTDDTE,
				CRTDBY = @CRTDBY,
				COMID = @COMID,
				EffectivityStartDate = @EffectivityStartDate,
				EffectivityEndDate = @EffectivityEndDate,
				IsActive = @IsActive
			WHERE CUSTOMERSHIPTOID = @CUSTOMERSHIPTOID
			SELECT @CUSTOMERSHIPTOID

		END
	End Else IF @Action = 'Delete' BEGIN

		DELETE FROM CustomerShipTo WHERE CUSTOMERSHIPTOID = @CUSTOMERSHIPTOID

	END
