-------------------------------------------------------------------------------------------------------
-- Generated By Althea Data Layer Generator Version 03022010. DO NOT REMOVE
-- Generated on 9/1/2012
------------------------------------------------------------------------------------------------------

Alter Procedure uspCustomer
	 @Action as Varchar(100) = '',
	 @CUSTOMERID AS INT = -1,
	 @CUSTOMERDEL AS BIT = 0,
	 @COMID AS VARCHAR(20) = '',
	 @CUSTOMERCD AS VARCHAR(20) = '',
	 @CUSTOMERNAME AS VARCHAR(255) = '',
	 @DISTRIBCD AS VARCHAR(20) = '',
	 @CADD1 AS VARCHAR(255) = '',
	 @CADD2 AS VARCHAR(255) = '',
	 @CMCONT AS VARCHAR(20) = '',
	 @CMPHON AS VARCHAR(20) = '',
	 @VAT AS BIT = 0,
	 @CDACD AS VARCHAR(20) = '',
	 @ZIPCD AS VARCHAR(20) = '',
	 @REGCD AS VARCHAR(20) = '',
	 @DISTCD AS VARCHAR(20) = '',
	 @AREACD AS VARCHAR(20) = '',
	 @TERRCD AS VARCHAR(20) = '',
	 @CMGRP AS VARCHAR(20) = '',
	 @CMCLASS AS VARCHAR(20) = '',
	 @AREACOVRG AS VARCHAR(20) = '',
	 @ACCNTSHRD AS BIT = 0,
	 @CRTDDTE AS DATETIME = '1/1/1900',
	 @CRTDBY AS VARCHAR(50) = '',
	 @EffectivityStartDate AS DATETIME = '1/1/1900',
	 @EffectivityEndDate AS DATETIME = '1/1/1900',
	 @IsActive AS BIT = 0

AS
	IF @Action = 'Save' BEGIN

		IF @CUSTOMERID = -1 BEGIN

			INSERT INTO Customer(CUSTOMERDEL, COMID, CUSTOMERCD, CUSTOMERNAME, DISTRIBCD, 
				CADD1, CADD2, CMCONT, CMPHON, VAT, 
				CDACD, ZIPCD, REGCD, DISTCD, AREACD, 
				TERRCD, CMGRP, CMCLASS, AREACOVRG, ACCNTSHRD, 
				CRTDDTE, CRTDBY, EffectivityStartDate, EffectivityEndDate, IsActive
				)
			VALUES(@CUSTOMERDEL, @COMID, @CUSTOMERCD, @CUSTOMERNAME, @DISTRIBCD, 
				@CADD1, @CADD2, @CMCONT, @CMPHON, @VAT, 
				@CDACD, @ZIPCD, @REGCD, @DISTCD, @AREACD, 
				@TERRCD, @CMGRP, @CMCLASS, @AREACOVRG, @ACCNTSHRD, 
				@CRTDDTE, @CRTDBY, @EffectivityStartDate, @EffectivityEndDate, @IsActive
				)
			SELECT @@IDENTITY

		END ELSE BEGIN

			UPDATE Customer SET CUSTOMERDEL = @CUSTOMERDEL,
				COMID = @COMID,
				CUSTOMERCD = @CUSTOMERCD,
				CUSTOMERNAME = @CUSTOMERNAME,
				DISTRIBCD = @DISTRIBCD,
				CADD1 = @CADD1,
				CADD2 = @CADD2,
				CMCONT = @CMCONT,
				CMPHON = @CMPHON,
				VAT = @VAT,
				CDACD = @CDACD,
				ZIPCD = @ZIPCD,
				REGCD = @REGCD,
				DISTCD = @DISTCD,
				AREACD = @AREACD,
				TERRCD = @TERRCD,
				CMGRP = @CMGRP,
				CMCLASS = @CMCLASS,
				AREACOVRG = @AREACOVRG,
				ACCNTSHRD = @ACCNTSHRD,
				CRTDDTE = @CRTDDTE,
				CRTDBY = @CRTDBY,
				EffectivityStartDate = @EffectivityStartDate,
				EffectivityEndDate = @EffectivityEndDate,
				IsActive = @IsActive
			WHERE CUSTOMERID = @CUSTOMERID
			SELECT @CUSTOMERID

		END
	End Else IF @Action = 'Delete' BEGIN

		DELETE FROM Customer WHERE CUSTOMERID = @CUSTOMERID

	END
