CREATE TABLE [dbo].[BillingOrderDetails](
	[BillingOrderDetailID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[BillingOrderID] [int] NOT NULL DEFAULT -1,
	[ItemID] [int] NOT NULL DEFAULT -1,
	[Quantity] [numeric](12, 6) NOT NULL DEFAULT 0,
	[UnitOfMeasureID] [int] NOT NULL DEFAULT -1,
	[Discount] [varchar](50) NOT NULL DEFAULT '',
	[Amount] [money] NOT NULL DEFAULT 0,
	[UnitPrice] [money] NOT NULL DEFAULT 0,
	[DiscountAmount] [money] NOT NULL DEFAULT 0,
	[WarehouseID] [int] NOT NULL DEFAULT -1,
	[WarehouseLocationID] [int] NOT NULL  DEFAULT -1,
	[Lot] [varchar](20) NOT NULL DEFAULT '',
	[ListPrice] [money] NOT NULL DEFAULT 0,
	[IsFreeGoods] [bit] NOT NULL DEFAULT 0,
	[ExpiryDate] [datetime] NOT NULL DEFAULT '01/01/1900',
	[ManufacturingDate] [datetime] NOT NULL DEFAULT '01/01/1900',
	[Remarks] [varchar](255) NOT NULL DEFAULT '',
	[RawDataID] [int] NOT NULL DEFAULT -1,
	[RawDataAmount] [money] NOT NULL DEFAULT 0,
	[NetAmount] [money] NOT NULL  DEFAULT 0,
	[FreeGoods] [numeric](12, 6) NOT NULL DEFAULT 0,
	[VatAmount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveAmount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveRawDataNetAmount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveGrossAmount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveDiscount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveDiscountPercentage] [numeric](12, 6) NOT NULL DEFAULT 0,
	[VatExclusiveRawDataNetAmount] [money] NOT NULL DEFAULT 0,
	[VatExclusiveGrossAmount] [money] NOT NULL DEFAULT 0,
	[VatExclusiveDiscount] [money] NOT NULL DEFAULT 0,
	[VatExclusiveDiscountPercentage] [numeric](12, 6) NOT NULL  DEFAULT 0)