CREATE TABLE [dbo].[BillingOrder](
	[BillingOrderID] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[BillingOrderNumber] [varchar](15) NOT NULL DEFAULT '',
	[CustomerId] [int] NOT NULL DEFAULT -1,
	[ShipToCustomerId] [int] NOT NULL DEFAULT -1,
	[Address] [varchar](255) NOT NULL DEFAULT '',
	[SalesManID] [int] NOT NULL DEFAULT -1,
	[SalesManCode] [varchar] (255) Not NULL DEFAULT -1,
	[TransactionDate] [datetime] NOT NULL DEFAULT '01/01/1900',
	[VatStatus] [char](1) NOT NULL DEFAULT '',
	[InvoiceNumber] [varchar](15) NOT NULL DEFAULT '',
	[InvoiceDate] [datetime] NOT NULL DEFAULT '01/01/1900',
	[CreditTermKey] [int] NOT NULL DEFAULT -1,
	[GrossTotal] [money] NOT NULL DEFAULT 0,
	[GrossDiscount] [money] NOT NULL DEFAULT 0,
	[NetTotal] [money] NOT NULL DEFAULT 0,
	[Status] [int] NOT NULL DEFAULT 0,
	[Remarks] [varchar](255) NOT NULL DEFAULT '',
	[CreatedBy] [int] NOT NULL DEFAULT -1,
	[CreateDate] [datetime] NOT NULL DEFAULT '01/01/1900',
	[LastModifiedBy] [int] NOT NULL DEFAULT -1,
	[LastModifiedDate] [datetime] NOT NULL DEFAULT '01/10/1900',
	[Source] [int] NOT NULL DEFAULT -1,
	[PriorityOrdinal] [int] NOT NULL DEFAULT -1,
	[OrderType] [int] NOT NULL DEFAULT -1,
	[RawDataID] [int] NOT NULL DEFAULT -1,
	[DistributorCode] [varchar](25) NOT NULL DEFAULT '',
	[ShipToCode] [varchar](25) NOT NULL DEFAULT '',
	[TransactionType] [tinyint] NOT NULL DEFAULT 0,
	[IsVatable] [bit] NOT NULL DEFAULT 0,
	[TotalVat] [money] NOT NULL DEFAULT 0,
	[InvoiceReferenceNumber] [varchar](100) NOT NULL DEFAULT '',
	[CMCode] [varchar](25) NOT NULL DEFAULT '',
	[ShipToName] [varchar](255) NOT NULL DEFAULT '',
	[ShipToAddress1] [varchar](255) NOT NULL DEFAULT '',
	[ShipToAddress2] [varchar](255) NOT NULL DEFAULT '',
	[VatInclusiveAmount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveRawDataNetAmount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveGrossAmount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveDiscount] [money] NOT NULL DEFAULT 0,
	[VatInclusiveDiscountPercentage] [numeric](12, 6) NOT NULL DEFAULT 0,
	[VatExclusiveRawDataNetAmount] [money] NOT NULL DEFAULT 0,
	[VatExclusiveGrossAmount] [money] NOT NULL DEFAULT 0,
	[VatExclusiveDiscount] [money] NOT NULL DEFAULT 0,
	[VatExclusiveDiscountPercentage] [numeric](12, 6) NOT NULL DEFAULT 0,
	[VatAmount] [money] NOT NULL DEFAULT 0,
	[RowVersion] [int] NOT NULL DEFAULT -1)