'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule

Public Class ExpenseDetails
    
    Private m_ExpenseDetailID As Integer = -1
    
    Private m_ExpenseID As Integer = -1
    
    Private m_ExpenseTypeCode As String = String.Empty
    
    Private m_ExpenseAmount As Double = 0
    
    Private m_VAT As Double = 0
    
    Private m_EWTValue As Double = 0

    Private m_ExpenseDate As Date = "1/1/1900"

    Private m_MarkForDelete As Boolean = False

    Private m_Remarks As String = String.Empty

    Public Property Remarks() As String
        Get
            Return m_Remarks
        End Get
        Set(ByVal value As String)
            m_Remarks = value
        End Set
    End Property

    Public Property MarkForDelete() As Boolean
        Get
            Return m_MarkForDelete
        End Get
        Set(ByVal value As Boolean)
            m_MarkForDelete = value
        End Set
    End Property
    
    Public ReadOnly Property ExpenseDetailID() As Integer
        Get
            Return m_ExpenseDetailID
        End Get
    End Property
    
    Public Property ExpenseID() As Integer
        Get
            Return m_ExpenseID
        End Get
        Set
            m_ExpenseID = value
        End Set
    End Property
    
    Public Property ExpenseTypeCode() As String
        Get
            Return m_ExpenseTypeCode
        End Get
        Set
            m_ExpenseTypeCode = value
        End Set
    End Property
    
    Public Property ExpenseAmount() As Double
        Get
            Return m_ExpenseAmount
        End Get
        Set
            m_ExpenseAmount = value
        End Set
    End Property
    
    Public Property VAT() As Double
        Get
            Return m_VAT
        End Get
        Set
            m_VAT = value
        End Set
    End Property
    
    Public Property EWTValue() As Double
        Get
            Return m_EWTValue
        End Get
        Set
            m_EWTValue = value
        End Set
    End Property
    Public Property ExpenseDate() As Date
        Get
            Return m_ExpenseDate
        End Get
        Set(ByVal value As Date)
            m_ExpenseDate = value
        End Set
    End Property
    Public Function Save() As Boolean

        If m_MarkForDelete = True Then
            If m_ExpenseDetailID = -1 Then
                Return True
            Else
                Delete()
            End If
        End If

        Connect()
        Try

            Dim cmd As New SqlCommand("uspExpenseDetails", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Save")
            cmd.Parameters.AddWithValue("@ExpenseDetailID", m_ExpenseDetailID)
            cmd.Parameters.AddWithValue("@ExpenseID", m_ExpenseID)
            cmd.Parameters.AddWithValue("@ExpenseTypeCode", m_ExpenseTypeCode)
            cmd.Parameters.AddWithValue("@ExpenseAmount", m_ExpenseAmount)
            cmd.Parameters.AddWithValue("@VAT", m_VAT)
            cmd.Parameters.AddWithValue("@ExpenseDate", m_ExpenseDate)
            cmd.Parameters.AddWithValue("@EWTValue", m_EWTValue)
            cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
            m_ExpenseDetailID = cmd.ExecuteScalar()
            Disconnect()
            Return True
        Catch ex As System.Exception
            Disconnect()
            Throw
        End Try
    End Function
    
    Public Function Delete() As Boolean
        Connect()
        Try 

            Dim cmd As New SqlCommand("uspExpenseDetails", SPMSConn2)
				cmd.CommandType = CommandType.StoredProcedure
				cmd.Parameters.AddWithValue("@Action", "Delete")
				cmd.Parameters.AddWithValue("@ExpenseDetailID", m_ExpenseDetailID)
				cmd.ExecuteNonQuery()
            Disconnect()
				Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function
    
    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As ExpenseDetailsCollection
        Dim col as New ExpenseDetailsCollection
        For j As Integer = 0 To table.Rows.Count - 1
        	Dim m_ExpenseDetails as New ExpenseDetails
        	Dim row as DataRow = table.Rows(j)
				m_ExpenseDetails.m_ExpenseDetailID = row("ExpenseDetailID")
				m_ExpenseDetails.m_ExpenseID = row("ExpenseID")
				m_ExpenseDetails.m_ExpenseTypeCode = row("ExpenseTypeCode")
				m_ExpenseDetails.m_ExpenseAmount = row("ExpenseAmount")
				m_ExpenseDetails.m_VAT = row("VAT")
            m_ExpenseDetails.m_EWTValue = row("EWTValue")
            m_ExpenseDetails.m_ExpenseDate = row("ExpenseDate")
            m_ExpenseDetails.Remarks = row("Remarks")
				col.Add(m_ExpenseDetails)
        Next
        Return col
    End Function
    
    Public Shared Function Filter(ByVal Condition As String) As ExpenseDetailsCollection
        Return BaseFilter(GetRecords("SELECT * FROM ExpenseDetails " & IIf(Condition <> "", " WHERE " & Condition, "")))
    End Function
    
    Public Overloads Shared Function Load() As ExpenseDetailsCollection
			Return Filter("")
    End Function
    
    Public Overloads Shared Function Load(ByVal ExpenseDetailID As Integer) As ExpenseDetails
			Return Filter("ExpenseDetailID = " & ExpenseDetailID)(0)
    End Function

    Public Shared Function LoadByExpenseID(ByVal ExpenseID As Integer) As ExpenseDetailsCollection
        Return Filter("ExpenseID = " & ExpenseID)
    End Function
    
End Class

Public Class ExpenseDetailsCollection
    
		Inherits List(Of ExpenseDetails)
End Class
