'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule

Public Class Expense
    
    Private m_ExpenseID As Integer = -1
    
    Private m_EntryNumber As String = String.Empty
    
    Private m_ExpenseDate As Date = "1/1/1900"
    
    Private m_SalesAgentCode As String = String.Empty
    
    Private m_Remarks As String = String.Empty
    
    Private m_VatInclusiveAmount As Double = 0
    
    Private m_VatExclusiveAmount As Double = 0
    
    Private m_TotalVat As Double = 0
    
    Private m_TotalEWT As Double = 0
    
    Private m_CreatedBy As Integer = 0
    
    Private m_CreateDate As Date = "1/1/1900"
    
    Private m_LastModifiedBy As Integer = 0
    
    Private m_LastModifiedDate As Date = "1/1/1900"
    
    Private m_ExpenseDetails As New ExpenseDetailsCollection

    Private m_Status As EnumExpenseStatus = EnumExpenseStatus.Pending

    Public Enum EnumExpenseStatus
        Pending = 0
        Approved = 1
    End Enum
    Public ReadOnly Property ExpenseID() As Integer
        Get
            Return m_ExpenseID
        End Get
    End Property
    
    Public Property EntryNumber() As String
        Get
            Return m_EntryNumber
        End Get
        Set
            m_EntryNumber = value
        End Set
    End Property
    
    Public Property ExpenseDate() As Date
        Get
            Return m_ExpenseDate
        End Get
        Set
            m_ExpenseDate = value
        End Set
    End Property
    
    Public Property SalesAgentCode() As String
        Get
            Return m_SalesAgentCode
        End Get
        Set
            m_SalesAgentCode = value
        End Set
    End Property
    
    Public Property Remarks() As String
        Get
            Return m_Remarks
        End Get
        Set
            m_Remarks = value
        End Set
    End Property
    
    Public Property VatInclusiveAmount() As Double
        Get
            Return m_VatInclusiveAmount
        End Get
        Set
            m_VatInclusiveAmount = value
        End Set
    End Property
    
    Public Property VatExclusiveAmount() As Double
        Get
            Return m_VatExclusiveAmount
        End Get
        Set
            m_VatExclusiveAmount = value
        End Set
    End Property
    
    Public Property TotalVat() As Double
        Get
            Return m_TotalVat
        End Get
        Set
            m_TotalVat = value
        End Set
    End Property
    
    Public Property TotalEWT() As Double
        Get
            Return m_TotalEWT
        End Get
        Set
            m_TotalEWT = value
        End Set
    End Property
    
    Public Property CreatedBy() As Integer
        Get
            Return m_CreatedBy
        End Get
        Set
            m_CreatedBy = value
        End Set
    End Property
    
    Public ReadOnly Property CreateDate() As Date
        Get
            Return m_CreateDate
        End Get
    End Property
    
    Public Property LastModifiedBy() As Integer
        Get
            Return m_LastModifiedBy
        End Get
        Set
            m_LastModifiedBy = value
        End Set
    End Property
    
    Public ReadOnly Property LastModifiedDate() As Date
        Get
            Return m_LastModifiedDate
        End Get
    End Property

    Public Property Status() As EnumExpenseStatus
        Get
            Return m_Status
        End Get
        Set(ByVal value As EnumExpenseStatus)
            m_Status = value
        End Set
    End Property

    Public ReadOnly Property ExpenseDetailsCollection() As ExpenseDetailsCollection
        Get
            Return m_ExpenseDetails
        End Get
    End Property
    
    Public Function Save() As Boolean
        Connect()
        Try 
            Dim cmd As New SqlCommand("uspExpense", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Save")
            cmd.Parameters.AddWithValue("@ExpenseID", m_ExpenseID)
            cmd.Parameters.AddWithValue("@EntryNumber", m_EntryNumber)
            cmd.Parameters.AddWithValue("@ExpenseDate", m_ExpenseDate)
            cmd.Parameters.AddWithValue("@SalesAgentCode", m_SalesAgentCode)
            cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
            cmd.Parameters.AddWithValue("@VatInclusiveAmount", m_VatInclusiveAmount)
            cmd.Parameters.AddWithValue("@VatExclusiveAmount", m_VatExclusiveAmount)
            cmd.Parameters.AddWithValue("@TotalVat", m_TotalVat)
            cmd.Parameters.AddWithValue("@TotalEWT", m_TotalEWT)
            cmd.Parameters.AddWithValue("@CreatedBy", m_CreatedBy)
            cmd.Parameters.AddWithValue("@CreateDate", m_CreateDate)
            cmd.Parameters.AddWithValue("@LastModifiedBy", m_LastModifiedBy)
            cmd.Parameters.AddWithValue("@LastModifiedDate", m_LastModifiedDate)
            cmd.Parameters.AddWithValue("@Status", m_Status)
            m_ExpenseID = cmd.ExecuteScalar()
            Disconnect()
				For j As Integer = 0 To m_ExpenseDetails.Count - 1
					m_ExpenseDetails(j).ExpenseID = m_ExpenseID
					If Not m_ExpenseDetails(j).Save Then
						Throw New Exception("Error saving ExpenseDetails Index " & j)
					End if
				Next
				Return True
        Catch ex As System.Exception
            Disconnect()
            Throw
        End Try
    End Function
    
    Public Function Delete() As Boolean
        Connect()
        Try 
				For j As Integer = 0 To m_ExpenseDetails.Count - 1
					If Not m_ExpenseDetails(j).Delete Then
						Throw New Exception("Error deleting ExpenseDetails Index " & j)
					End If
				Next

            Dim cmd As New SqlCommand("uspExpense", SPMSConn2)
				cmd.CommandType = CommandType.StoredProcedure
				cmd.Parameters.AddWithValue("@Action", "Delete")
				cmd.Parameters.AddWithValue("@ExpenseID", m_ExpenseID)
				cmd.ExecuteNonQuery()

				Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function
    
    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As ExpenseCollection
        Dim col as New ExpenseCollection
        For j As Integer = 0 To table.Rows.Count - 1
        	Dim m_Expense as New Expense
        	Dim row as DataRow = table.Rows(j)
				m_Expense.m_ExpenseID = row("ExpenseID")
				m_Expense.m_EntryNumber = row("EntryNumber")
				m_Expense.m_ExpenseDate = row("ExpenseDate")
				m_Expense.m_SalesAgentCode = row("SalesAgentCode")
				m_Expense.m_Remarks = row("Remarks")
				m_Expense.m_VatInclusiveAmount = row("VatInclusiveAmount")
				m_Expense.m_VatExclusiveAmount = row("VatExclusiveAmount")
				m_Expense.m_TotalVat = row("TotalVat")
				m_Expense.m_TotalEWT = row("TotalEWT")
				m_Expense.m_CreatedBy = row("CreatedBy")
				m_Expense.m_CreateDate = row("CreateDate")
				m_Expense.m_LastModifiedBy = row("LastModifiedBy")
            m_Expense.m_LastModifiedDate = row("LastModifiedDate")
            m_Expense.m_Status = row("Status")
            m_Expense.m_ExpenseDetails = ExpenseDetails.LoadByExpenseID(m_Expense.m_ExpenseID)
				col.Add(m_Expense)
        Next
        Return col
    End Function
    
    Public Shared Function Filter(ByVal Condition As String) As ExpenseCollection
        Return BaseFilter(GetRecords("SELECT * FROM Expense " & IIf(Condition <> "", " WHERE " & Condition, "")))
    End Function
    
    Public Overloads Shared Function Load() As ExpenseCollection
			Return Filter("")
    End Function
    
    Public Overloads Shared Function Load(ByVal ExpenseID As Integer) As Expense
			Return Filter("ExpenseID = " & ExpenseID)(0)
    End Function

    Public Shared Function GetExpenseSql() As String
        Return "SELECT ExpenseID, EntryNumber [Expense No.], ExpenseDate [Expense Date], SLSMNNAME [Sales Agent], 	Remarks ,  	Case Status WHEN 0 THEN 'Pending' WHEN 1 THEN 'Approved' END as Status FROM 	EXPENSE A, 	MedicalRep B WHERE B.SLSMNCd = A.SalesAgentCode AND B.DLTFLG = 0 "
    End Function

    Public Shared Function GetExpenseColumns() As String
        Return "ExpenseID; EntryNumber; ExpenseDate; SLSMNNAME; Remarks; Status;"
    End Function
End Class

Public Class ExpenseCollection
    
		Inherits List(Of Expense)
End Class
