'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule

Public Class Particulars
    
    Private m_ParticularID As Integer = -1
    
    Private m_DLTFLG As Boolean = False
    
    Private m_ParentCode As String = String.Empty
    
    Private m_Code As String = String.Empty
    
    Private m_Description As String = String.Empty
    
    Private m_Type As Short = 0
    
    Private m_CreatedBy As Integer = 0
    
    Private m_CreateDate As Date = "1/1/1900"
    
    Private m_LastModifiedBy As Integer = 0
    
    Private m_LastModifiedDate As Date = "1/1/1900"

    Private m_Level As Integer = 1

    Public Property Level() As Integer
        Get
            Return m_Level
        End Get
        Set(ByVal value As Integer)
            m_Level = value
        End Set
    End Property

    Public Enum EnumParticularType
        None = -1
        Specialty = 0
        CoverageLeave = 1
        Expense = 3
    End Enum

    Public ReadOnly Property ParticularID() As Integer
        Get
            Return m_ParticularID
        End Get
    End Property
    
    Public Property DLTFLG() As Boolean
        Get
            Return m_DLTFLG
        End Get
        Set
            m_DLTFLG = value
        End Set
    End Property
    
    Public Property ParentCode() As String
        Get
            Return m_ParentCode
        End Get
        Set
            m_ParentCode = value
        End Set
    End Property
    
    Public Property Code() As String
        Get
            Return m_Code
        End Get
        Set
            m_Code = value
        End Set
    End Property
    
    Public Property Description() As String
        Get
            Return m_Description
        End Get
        Set
            m_Description = value
        End Set
    End Property
    
    Public Property Type() As EnumParticularType
        Get
            Return m_Type
        End Get
        Set(ByVal value As EnumParticularType)
            m_Type = Value
        End Set
    End Property
    
    Public Property CreatedBy() As Integer
        Get
            Return m_CreatedBy
        End Get
        Set
            m_CreatedBy = value
        End Set
    End Property
    
    Public ReadOnly Property CreateDate() As Date
        Get
            Return m_CreateDate
        End Get
    End Property
    
    Public Property LastModifiedBy() As Integer
        Get
            Return m_LastModifiedBy
        End Get
        Set
            m_LastModifiedBy = value
        End Set
    End Property
    
    Public ReadOnly Property LastModifiedDate() As Date
        Get
            Return m_LastModifiedDate
        End Get
    End Property
    
    Public Function Save() As Boolean

        Try 
            Connect()
            Dim cmd As New SqlCommand("uspParticulars", SPMSConn2)
				cmd.CommandType = CommandType.StoredProcedure
				cmd.Parameters.AddWithValue("@Action", "Save")
				cmd.Parameters.AddWithValue("@ParticularID", m_ParticularID)
				cmd.Parameters.AddWithValue("@DLTFLG", m_DLTFLG)
				cmd.Parameters.AddWithValue("@ParentCode", m_ParentCode)
				cmd.Parameters.AddWithValue("@Code", m_Code)
				cmd.Parameters.AddWithValue("@Description", m_Description)
				cmd.Parameters.AddWithValue("@Type", m_Type)
				cmd.Parameters.AddWithValue("@CreatedBy", m_CreatedBy)
				cmd.Parameters.AddWithValue("@CreateDate", m_CreateDate)
				cmd.Parameters.AddWithValue("@LastModifiedBy", m_LastModifiedBy)
            cmd.Parameters.AddWithValue("@LastModifiedDate", m_LastModifiedDate)
            cmd.Parameters.AddWithValue("@Level", m_Level)
				m_ParticularID = cmd.ExecuteScalar()
            Disconnect()
				Return True
        Catch ex As System.Exception
            Disconnect()
            Throw
        End Try
    End Function
    
    Public Function Delete() As Boolean

        Try 
            Connect()
            Dim cmd As New SqlCommand("uspParticulars", SPMSConn2)
				cmd.CommandType = CommandType.StoredProcedure
				cmd.Parameters.AddWithValue("@Action", "Delete")
				cmd.Parameters.AddWithValue("@ParticularID", m_ParticularID)
				cmd.ExecuteNonQuery()
            Disconnect()
				Return True
        Catch ex As System.Exception

        End Try
    End Function
    
    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As ParticularsCollection
        Dim col as New ParticularsCollection
        For j As Integer = 0 To table.Rows.Count - 1
        	Dim m_Particulars as New Particulars
        	Dim row as DataRow = table.Rows(j)
				m_Particulars.m_ParticularID = row("ParticularID")
				m_Particulars.m_DLTFLG = row("DLTFLG")
				m_Particulars.m_ParentCode = row("ParentCode")
				m_Particulars.m_Code = row("Code")
				m_Particulars.m_Description = row("Description")
				m_Particulars.m_Type = row("Type")
				m_Particulars.m_CreatedBy = row("CreatedBy")
				m_Particulars.m_CreateDate = row("CreateDate")
				m_Particulars.m_LastModifiedBy = row("LastModifiedBy")
            m_Particulars.m_LastModifiedDate = row("LastModifiedDate")
            m_Particulars.m_Level = row("Level")
				col.Add(m_Particulars)
        Next
        Return col
    End Function
    
    Public Shared Function Filter(ByVal Condition As String) As ParticularsCollection
        Return BaseFilter(GetRecords("SELECT * FROM Particulars WHERE DLTFLG = 0 " & IIf(Condition <> "", " AND " & Condition, "")))
    End Function
    
    Public Overloads Shared Function Load() As ParticularsCollection
			Return Filter("")
    End Function
    
    Public Overloads Shared Function Load(ByVal ParticularID As Integer) As Particulars
			Return Filter("ParticularID = " & ParticularID)(0)
    End Function

    Public Shared Function LoadByCode(ByVal Code As String, ByVal Type As EnumParticularType) As Particulars
        Return Filter("Code = '" & HandleSingleQuoteInSql(Code) & "'   AND Type = " & Type)(0)
    End Function

    Public Shared Function GetLevel(ByVal Code As String, ByVal Type As EnumParticularType) As Integer
        Return LoadByCode(Code, Type).Level
    End Function

    Public Shared Function GetParticualrDescription(ByVal ParticularCode As String, ByVal ParticularType As EnumParticularType) As String
        Return Filter("Code = '" & HandleSingleQuoteInSql(ParticularCode) & "' AND Type = " & ParticularType)(0).Description
    End Function

    Public Shared Function CheckIfCodeAlreadyExist(ByVal Code As String, ByVal ParticularID As Integer, ByVal ParticularType As EnumParticularType) As Boolean
        Return ExecuteCommand("SELECT 'A' FROM Particulars WHERE DLTFLG = 0 AND   Type = " & ParticularType & "   AND Code = '" & HandleSingleQuoteInSql(Code) & "' AND ParticularID <> " & ParticularID) = "A"
    End Function

    Public Shared Function GetParticularsSQL(Optional ByVal Type As EnumParticularType = EnumParticularType.None) As String
        Return "SELECT ParticularID, ParentCode [Parent Code], Code, Description , CASE Type WHEN 0 THEN 'Specialty'  WHEN 1 THEN 'Coverage Leave'  WHEN 3 THEN 'Expense' END as Type FROM Particulars WHERE DLTFLG = 0 " & IIf(Type <> EnumParticularType.None, "AND  Type = " & Type, "")
    End Function

    Public Shared Function GetParticularsSQLForSpecialty(Optional ByVal Type As EnumParticularType = EnumParticularType.None) As String
        Return "SELECT ParticularID,  Code [Specialty Code], Description [Specialty Description] , CASE Type WHEN 0 THEN 'Specialty'  WHEN 1 THEN 'Coverage Leave' WHEN 3 THEN 'Expense'  END as Type FROM Particulars WHERE ParentCode = '' AND DLTFLG = 0 " & IIf(Type <> EnumParticularType.None, "AND  Type = " & Type, "")
    End Function

    Public Shared Function GetParticularsSQLForSubSpecialty(ByVal ParentCode As String, Optional ByVal Type As EnumParticularType = EnumParticularType.None) As String
        Return "SELECT ParticularID, ParentCode [Specialty Code], Code [Sub - specialty Code], Description  [Sub - specialty Description], CASE Type WHEN 0 THEN 'Specialty'  WHEN 1 THEN 'Coverage Leave' WHEN 3 THEN 'Expense'  END as Type FROM Particulars WHERE ParentCode = '" & ParentCode & "' AND DLTFLG = 0 " & IIf(Type <> EnumParticularType.None, "AND  Type = " & Type, "")
    End Function

    Public Shared Function GetParticularsColumns() As String
        Return "ParticularID; ParentCode; Code; Description; Type"
    End Function

    Public Shared Function GetParticularsColumnsForSpecialty() As String
        Return "ParticularID; Code; Description; Type"
    End Function
End Class

Public Class ParticularsCollection
    
		Inherits List(Of Particulars)
End Class
