'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule


Public Class BillingOrder

    Public Const BillingOrderTableConstant As String = "BillingOrder"

    Private m_BillingOrderID As Integer = -1

    Private m_BillingOrderNumber As String = String.Empty

    Private m_CustomerId As Integer = 0

    Private m_ShipToCustomerId As Integer = 0

    Private m_Address As String = String.Empty

    Private m_SalesManID As Integer = -1

    Private m_SalesManCode As String = String.Empty

    Private m_TransactionDate As Date = "1/1/1900"

    Private m_VatStatus As String = String.Empty

    Private m_InvoiceNumber As String = String.Empty

    Private m_InvoiceDate As Date = "1/1/1900"

    Private m_CreditTermKey As Integer = -1

    Private m_GrossTotal As Double = 0

    Private m_GrossDiscount As Double = 0

    Private m_NetTotal As Double = 0

    Private m_Status As Integer = 0

    Private m_Remarks As String = String.Empty

    Private m_CreatedBy As Integer = 0

    Private m_CreateDate As Date = "1/1/1900"

    Private m_LastModifiedBy As Integer = 0

    Private m_LastModifiedDate As Date = "1/1/1900"

    Private m_Source As Integer = 0

    Private m_PriorityOrdinal As Integer = 0

    Private m_OrderType As Integer = 0

    Private m_RawDataID As Integer = -1

    Private m_DistributorCode As String = String.Empty

    Private m_ShipToCode As String = String.Empty

    Private m_TransactionType As Short = 0

    Private m_IsVatable As Boolean = False

    Private m_TotalVat As Double = 0

    Private m_InvoiceReferenceNumber As String = String.Empty

    Private m_CMCode As String = String.Empty

    Private m_ShipToName As String = String.Empty

    Private m_ShipToAddress1 As String = String.Empty

    Private m_ShipToAddress2 As String = String.Empty

    Private m_VatInclusiveAmount As Double = 0

    Private m_VatInclusiveRawDataNetAmount As Double = 0

    Private m_VatInclusiveGrossAmount As Double = 0

    Private m_VatInclusiveDiscount As Double = 0

    Private m_VatInclusiveDiscountPercentage As Decimal = 0

    Private m_VatExclusiveRawDataNetAmount As Double = 0

    Private m_VatExclusiveGrossAmount As Double = 0

    Private m_VatExclusiveDiscount As Double = 0

    Private m_VatExclusiveDiscountPercentage As Decimal = 0

    Private m_VatAmount As Double = 0

    Private m_RowVersion As Integer = 0

    Private m_BillingOrderDetails As New BillingOrderDetailsCollection


    Public Enum EnumBillingOrderStatus
        Pending = 0
        Finalized = 1
        Canceled = 2
    End Enum

    Public ReadOnly Property BillingOrderID() As Integer
        Get
            Return m_BillingOrderID
        End Get
    End Property

    Public Property BillingOrderNumber() As String
        Get
            Return m_BillingOrderNumber
        End Get
        Set(ByVal value As String)
            m_BillingOrderNumber = value
        End Set
    End Property

    Public Property CustomerId() As Integer
        Get
            Return m_CustomerId
        End Get
        Set(ByVal value As Integer)
            m_CustomerId = value
        End Set
    End Property

    Public Property ShipToCustomerId() As Integer
        Get
            Return m_ShipToCustomerId
        End Get
        Set(ByVal value As Integer)
            m_ShipToCustomerId = value
        End Set
    End Property

    Public Property Address() As String
        Get
            Return m_Address
        End Get
        Set(ByVal value As String)
            m_Address = value
        End Set
    End Property

    Public Property SalesManID() As Integer
        Get
            Return m_SalesManID
        End Get
        Set(ByVal value As Integer)
            m_SalesManID = value
        End Set
    End Property
    Public Property SalesManCode() As String
        Get
            Return m_SalesManCode
        End Get
        Set(ByVal value As String)
            m_SalesManCode = value
        End Set
    End Property

    Public Property TransactionDate() As Date
        Get
            Return m_TransactionDate
        End Get
        Set(ByVal value As Date)
            m_TransactionDate = value
        End Set
    End Property

    Public Property VatStatus() As String
        Get
            Return m_VatStatus
        End Get
        Set(ByVal value As String)
            m_VatStatus = value
        End Set
    End Property

    Public Property InvoiceNumber() As String
        Get
            Return m_InvoiceNumber
        End Get
        Set(ByVal value As String)
            m_InvoiceNumber = value
        End Set
    End Property

    Public Property InvoiceDate() As Date
        Get
            Return m_InvoiceDate
        End Get
        Set(ByVal value As Date)
            m_InvoiceDate = value
        End Set
    End Property

    Public Property CreditTermKey() As Integer
        Get
            Return m_CreditTermKey
        End Get
        Set(ByVal value As Integer)
            m_CreditTermKey = value
        End Set
    End Property

    Public Property GrossTotal() As Double
        Get
            Return m_GrossTotal
        End Get
        Set(ByVal value As Double)
            m_GrossTotal = value
        End Set
    End Property

    Public Property GrossDiscount() As Double
        Get
            Return m_GrossDiscount
        End Get
        Set(ByVal value As Double)
            m_GrossDiscount = value
        End Set
    End Property

    Public Property NetTotal() As Double
        Get
            Return m_NetTotal
        End Get
        Set(ByVal value As Double)
            m_NetTotal = value
        End Set
    End Property

    Public Property Status() As Integer
        Get
            Return m_Status
        End Get
        Set(ByVal value As Integer)
            m_Status = value
        End Set
    End Property

    Public Property Remarks() As String
        Get
            Return m_Remarks
        End Get
        Set(ByVal value As String)
            m_Remarks = value
        End Set
    End Property

    Public Property CreatedBy() As Integer
        Get
            Return m_CreatedBy
        End Get
        Set(ByVal value As Integer)
            m_CreatedBy = value
        End Set
    End Property

    Public ReadOnly Property CreateDate() As Date
        Get
            Return m_CreateDate
        End Get
    End Property

    Public Property LastModifiedBy() As Integer
        Get
            Return m_LastModifiedBy
        End Get
        Set(ByVal value As Integer)
            m_LastModifiedBy = value
        End Set
    End Property

    Public ReadOnly Property LastModifiedDate() As Date
        Get
            Return m_LastModifiedDate
        End Get
    End Property

    Public Property Source() As Integer
        Get
            Return m_Source
        End Get
        Set(ByVal value As Integer)
            m_Source = value
        End Set
    End Property

    Public Property PriorityOrdinal() As Integer
        Get
            Return m_PriorityOrdinal
        End Get
        Set(ByVal value As Integer)
            m_PriorityOrdinal = value
        End Set
    End Property

    Public Property OrderType() As Integer
        Get
            Return m_OrderType
        End Get
        Set(ByVal value As Integer)
            m_OrderType = value
        End Set
    End Property

    Public Property RawDataID() As Integer
        Get
            Return m_RawDataID
        End Get
        Set(ByVal value As Integer)
            m_RawDataID = value
        End Set
    End Property

    Public Property DistributorCode() As String
        Get
            Return m_DistributorCode
        End Get
        Set(ByVal value As String)
            m_DistributorCode = value
        End Set
    End Property

    Public Property ShipToCode() As String
        Get
            Return m_ShipToCode
        End Get
        Set(ByVal value As String)
            m_ShipToCode = value
        End Set
    End Property

    Public Property TransactionType() As Short
        Get
            Return m_TransactionType
        End Get
        Set(ByVal value As Short)
            m_TransactionType = value
        End Set
    End Property

    Public Property IsVatable() As Boolean
        Get
            Return m_IsVatable
        End Get
        Set(ByVal value As Boolean)
            m_IsVatable = value
        End Set
    End Property

    Public Property TotalVat() As Double
        Get
            Return m_TotalVat
        End Get
        Set(ByVal value As Double)
            m_TotalVat = value
        End Set
    End Property

    Public Property InvoiceReferenceNumber() As String
        Get
            Return m_InvoiceReferenceNumber
        End Get
        Set(ByVal value As String)
            m_InvoiceReferenceNumber = value
        End Set
    End Property

    Public Property CMCode() As String
        Get
            Return m_CMCode
        End Get
        Set(ByVal value As String)
            m_CMCode = value
        End Set
    End Property

    Public Property ShipToName() As String
        Get
            Return m_ShipToName
        End Get
        Set(ByVal value As String)
            m_ShipToName = value
        End Set
    End Property

    Public Property ShipToAddress1() As String
        Get
            Return m_ShipToAddress1
        End Get
        Set(ByVal value As String)
            m_ShipToAddress1 = value
        End Set
    End Property

    Public Property ShipToAddress2() As String
        Get
            Return m_ShipToAddress2
        End Get
        Set(ByVal value As String)
            m_ShipToAddress2 = value
        End Set
    End Property

    Public Property VatInclusiveAmount() As Double
        Get
            Return m_VatInclusiveAmount
        End Get
        Set(ByVal value As Double)
            m_VatInclusiveAmount = value
        End Set
    End Property

    Public Property VatInclusiveRawDataNetAmount() As Double
        Get
            Return m_VatInclusiveRawDataNetAmount
        End Get
        Set(ByVal value As Double)
            m_VatInclusiveRawDataNetAmount = value
        End Set
    End Property

    Public Property VatInclusiveGrossAmount() As Double
        Get
            Return m_VatInclusiveGrossAmount
        End Get
        Set(ByVal value As Double)
            m_VatInclusiveGrossAmount = value
        End Set
    End Property

    Public Property VatInclusiveDiscount() As Double
        Get
            Return m_VatInclusiveDiscount
        End Get
        Set(ByVal value As Double)
            m_VatInclusiveDiscount = value
        End Set
    End Property

    Public Property VatInclusiveDiscountPercentage() As Decimal
        Get
            Return m_VatInclusiveDiscountPercentage
        End Get
        Set(ByVal value As Decimal)
            m_VatInclusiveDiscountPercentage = value
        End Set
    End Property

    Public Property VatExclusiveRawDataNetAmount() As Double
        Get
            Return m_VatExclusiveRawDataNetAmount
        End Get
        Set(ByVal value As Double)
            m_VatExclusiveRawDataNetAmount = value
        End Set
    End Property

    Public Property VatExclusiveGrossAmount() As Double
        Get
            Return m_VatExclusiveGrossAmount
        End Get
        Set(ByVal value As Double)
            m_VatExclusiveGrossAmount = value
        End Set
    End Property

    Public Property VatExclusiveDiscount() As Double
        Get
            Return m_VatExclusiveDiscount
        End Get
        Set(ByVal value As Double)
            m_VatExclusiveDiscount = value
        End Set
    End Property

    Public Property VatExclusiveDiscountPercentage() As Decimal
        Get
            Return m_VatExclusiveDiscountPercentage
        End Get
        Set(ByVal value As Decimal)
            m_VatExclusiveDiscountPercentage = value
        End Set
    End Property

    Public Property VatAmount() As Double
        Get
            Return m_VatAmount
        End Get
        Set(ByVal value As Double)
            m_VatAmount = value
        End Set
    End Property

    Public ReadOnly Property RowVersion() As Integer
        Get
            Return m_RowVersion
        End Get
    End Property

    Public ReadOnly Property BillingOrderDetailsCollection() As BillingOrderDetailsCollection
        Get
            Return m_BillingOrderDetails
        End Get
    End Property


    Public Function Finalized() As Boolean
        m_Status = EnumBillingOrderStatus.Finalized
        If Save() Then
            Return True
        End If
    End Function

    Public Function Canceled() As Boolean
        m_Status = EnumBillingOrderStatus.Canceled
        If Save() Then
            Return True
        End If
    End Function

    Public Function Save() As Boolean
        If SPMSConn2.State = ConnectionState.Closed Or SPMSConn2.State = ConnectionState.Broken Then Connect()

        'Try
        Dim cmd As New SqlCommand("uspBillingOrder", SPMSOPCI.ConnectionModule.SPMSConn2)
        cmd.CommandType = CommandType.StoredProcedure
        cmd.Parameters.AddWithValue("@Action", "Save")
        cmd.Parameters.AddWithValue("@BillingOrderID", m_BillingOrderID)
        cmd.Parameters.AddWithValue("@BillingOrderNumber", m_BillingOrderNumber)
        cmd.Parameters.AddWithValue("@CustomerId", m_CustomerId)
        cmd.Parameters.AddWithValue("@ShipToCustomerId", m_ShipToCustomerId)
        cmd.Parameters.AddWithValue("@Address", m_Address)
        cmd.Parameters.AddWithValue("@SalesManID", m_SalesManID)
        cmd.Parameters.AddWithValue("@SalesManCode", m_SalesManCode)
        cmd.Parameters.AddWithValue("@TransactionDate", m_TransactionDate)
        cmd.Parameters.AddWithValue("@VatStatus", m_VatStatus)
        cmd.Parameters.AddWithValue("@InvoiceNumber", m_InvoiceNumber)
        cmd.Parameters.AddWithValue("@InvoiceDate", m_InvoiceDate)
        cmd.Parameters.AddWithValue("@CreditTermKey", m_CreditTermKey)
        cmd.Parameters.AddWithValue("@GrossTotal", m_GrossTotal)
        cmd.Parameters.AddWithValue("@GrossDiscount", m_GrossDiscount)
        cmd.Parameters.AddWithValue("@NetTotal", m_NetTotal)
        cmd.Parameters.AddWithValue("@Status", m_Status)
        cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
        cmd.Parameters.AddWithValue("@CreatedBy", m_CreatedBy)
        cmd.Parameters.AddWithValue("@CreateDate", m_CreateDate)
        cmd.Parameters.AddWithValue("@LastModifiedBy", m_LastModifiedBy)
        cmd.Parameters.AddWithValue("@LastModifiedDate", m_LastModifiedDate)
        cmd.Parameters.AddWithValue("@Source", m_Source)
        cmd.Parameters.AddWithValue("@PriorityOrdinal", m_PriorityOrdinal)
        cmd.Parameters.AddWithValue("@OrderType", m_OrderType)
        cmd.Parameters.AddWithValue("@RawDataID", m_RawDataID)
        cmd.Parameters.AddWithValue("@DistributorCode", m_DistributorCode)
        cmd.Parameters.AddWithValue("@ShipToCode", m_ShipToCode)
        cmd.Parameters.AddWithValue("@TransactionType", m_TransactionType)
        cmd.Parameters.AddWithValue("@IsVatable", m_IsVatable)
        cmd.Parameters.AddWithValue("@TotalVat", m_TotalVat)
        cmd.Parameters.AddWithValue("@InvoiceReferenceNumber", m_InvoiceReferenceNumber)
        cmd.Parameters.AddWithValue("@CMCode", m_CMCode)
        cmd.Parameters.AddWithValue("@ShipToName", m_ShipToName)
        cmd.Parameters.AddWithValue("@ShipToAddress1", m_ShipToAddress1)
        cmd.Parameters.AddWithValue("@ShipToAddress2", m_ShipToAddress2)
        cmd.Parameters.AddWithValue("@VatInclusiveAmount", m_VatInclusiveAmount)
        cmd.Parameters.AddWithValue("@VatInclusiveRawDataNetAmount", m_VatInclusiveRawDataNetAmount)
        cmd.Parameters.AddWithValue("@VatInclusiveGrossAmount", m_VatInclusiveGrossAmount)
        cmd.Parameters.AddWithValue("@VatInclusiveDiscount", m_VatInclusiveDiscount)
        cmd.Parameters.AddWithValue("@VatInclusiveDiscountPercentage", m_VatInclusiveDiscountPercentage)
        cmd.Parameters.AddWithValue("@VatExclusiveRawDataNetAmount", m_VatExclusiveRawDataNetAmount)
        cmd.Parameters.AddWithValue("@VatExclusiveGrossAmount", m_VatExclusiveGrossAmount)
        cmd.Parameters.AddWithValue("@VatExclusiveDiscount", m_VatExclusiveDiscount)
        cmd.Parameters.AddWithValue("@VatExclusiveDiscountPercentage", m_VatExclusiveDiscountPercentage)
        cmd.Parameters.AddWithValue("@VatAmount", m_VatAmount)
        cmd.Parameters.AddWithValue("@RowVersion", m_RowVersion)
        m_BillingOrderID = cmd.ExecuteScalar()
        Disconnect()
        For j As Integer = 0 To m_BillingOrderDetails.Count - 1
            m_BillingOrderDetails(j).BillingOrderID = m_BillingOrderID
            If Not m_BillingOrderDetails(j).Save Then
                Throw New Exception("Error saving PurchaseOrderDetail Index " & j)
            End If
        Next
        Return True
        'Catch ex As System.Exception
        '    Disconnect()
        '    Throw
        'End Try
    End Function

    Public Function Delete() As Boolean

        Try
            For j As Integer = 0 To m_BillingOrderDetails.Count - 1
                If Not m_BillingOrderDetails(j).Delete Then
                    Throw New Exception("Error deleting BillingOrderDetails Index " & j)
                End If
            Next
            Connect()
            Dim cmd As New SqlCommand("uspBillingOrder", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Delete")
            cmd.Parameters.AddWithValue("@BillingOrderID", m_BillingOrderID)
            cmd.ExecuteNonQuery()
            Disconnect()
            Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function

    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As BillingOrderCollection
        Dim col As New BillingOrderCollection
        For j As Integer = 0 To table.Rows.Count - 1
            Dim m_BillingOrder As New BillingOrder
            Dim row As DataRow = table.Rows(j)
            m_BillingOrder.m_BillingOrderID = row("BillingOrderID")
            m_BillingOrder.m_BillingOrderNumber = row("BillingOrderNumber")
            m_BillingOrder.m_CustomerId = row("CustomerId")
            m_BillingOrder.m_ShipToCustomerId = row("ShipToCustomerId")
            m_BillingOrder.m_Address = row("Address")
            m_BillingOrder.m_SalesManID = row("SalesManID")
            m_BillingOrder.m_SalesManCode = row("SalesManCode")
            m_BillingOrder.m_TransactionDate = row("TransactionDate")
            m_BillingOrder.m_VatStatus = row("VatStatus")
            m_BillingOrder.m_InvoiceNumber = row("InvoiceNumber")
            m_BillingOrder.m_InvoiceDate = row("InvoiceDate")
            m_BillingOrder.m_CreditTermKey = row("CreditTermKey")
            m_BillingOrder.m_GrossTotal = row("GrossTotal")
            m_BillingOrder.m_GrossDiscount = row("GrossDiscount")
            m_BillingOrder.m_NetTotal = row("NetTotal")
            m_BillingOrder.m_Status = row("Status")
            m_BillingOrder.m_Remarks = row("Remarks")
            m_BillingOrder.m_CreatedBy = row("CreatedBy")
            m_BillingOrder.m_CreateDate = row("CreateDate")
            m_BillingOrder.m_LastModifiedBy = row("LastModifiedBy")
            m_BillingOrder.m_LastModifiedDate = row("LastModifiedDate")
            m_BillingOrder.m_Source = row("Source")
            m_BillingOrder.m_PriorityOrdinal = row("PriorityOrdinal")
            m_BillingOrder.m_OrderType = row("OrderType")
            m_BillingOrder.m_RawDataID = row("RawDataID")
            m_BillingOrder.m_DistributorCode = row("DistributorCode")
            m_BillingOrder.m_ShipToCode = row("ShipToCode")
            m_BillingOrder.m_TransactionType = row("TransactionType")
            m_BillingOrder.m_IsVatable = row("IsVatable")
            m_BillingOrder.m_TotalVat = row("TotalVat")
            m_BillingOrder.m_InvoiceReferenceNumber = row("InvoiceReferenceNumber")
            m_BillingOrder.m_CMCode = row("CMCode")
            m_BillingOrder.m_ShipToName = row("ShipToName")
            m_BillingOrder.m_ShipToAddress1 = row("ShipToAddress1")
            m_BillingOrder.m_ShipToAddress2 = row("ShipToAddress2")
            m_BillingOrder.m_VatInclusiveAmount = row("VatInclusiveAmount")
            m_BillingOrder.m_VatInclusiveRawDataNetAmount = row("VatInclusiveRawDataNetAmount")
            m_BillingOrder.m_VatInclusiveGrossAmount = row("VatInclusiveGrossAmount")
            m_BillingOrder.m_VatInclusiveDiscount = row("VatInclusiveDiscount")
            m_BillingOrder.m_VatInclusiveDiscountPercentage = row("VatInclusiveDiscountPercentage")
            m_BillingOrder.m_VatExclusiveRawDataNetAmount = row("VatExclusiveRawDataNetAmount")
            m_BillingOrder.m_VatExclusiveGrossAmount = row("VatExclusiveGrossAmount")
            m_BillingOrder.m_VatExclusiveDiscount = row("VatExclusiveDiscount")
            m_BillingOrder.m_VatExclusiveDiscountPercentage = row("VatExclusiveDiscountPercentage")
            m_BillingOrder.m_VatAmount = row("VatAmount")
            m_BillingOrder.m_RowVersion = row("RowVersion")
            m_BillingOrder.m_BillingOrderDetails = BillingOrderDetails.LoadByBillingOrder(m_BillingOrder.BillingOrderID)
            col.Add(m_BillingOrder)
        Next
        Return col
    End Function

    Public Shared Function Filter(ByVal Condition As String) As BillingOrderCollection
        Return BaseFilter(GetRecords("SELECT * FROM BillingOrder " & IIf(Condition <> "", "where " & Condition, "")))
    End Function

    Public Overloads Shared Function Load() As BillingOrderCollection
        Return Filter("")
    End Function

    Public Overloads Shared Function Load(ByVal BillingOrderID As Integer) As BillingOrder
        Return Filter("BillingOrderID = " & BillingOrderID)(0)
    End Function

    Public Shared Function GetBillingOrderSql() As String
        Return "Select A.BillingOrderID,A.BillingOrderNumber, B.CUSTOMERCD  [CustomerCode],B.CUSTOMERNAME,A.TransactionDate  [Transaction Date] from BillingOrder A, Customer B where A.CustomerId = B.CUSTOMERID"
    End Function

    Public Shared Function GetBillingOrderColumns() As String
        Return "BillingOrderID; BillingOrderNumber; CustomerCd;CustomerName;TransactionDate;"
    End Function

End Class

Public Class BillingOrderCollection

    Inherits List(Of BillingOrder)
End Class
