'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule


Public Class BillingOrderDetails

    Public Const BillingOrderDetailsTableConstant As String = "BillingOrderDetails"

    Private m_BillingOrderDetailID As Integer = -1

    Private m_BillingOrderID As Integer = -1

    Private m_ItemID As String = String.Empty

    Private m_Quantity As Decimal = 0

    Private m_UnitOfMeasureID As Integer = -1

    Private m_Discount As String = String.Empty

    Private m_Amount As Double = 0

    Private m_VatExcusiveRawDataAmount As Double = 0

    Private m_UnitPrice As Double = 0

    Private m_DiscountAmount As Double = 0

    Private m_WarehouseID As Integer = -1

    Private m_WarehouseLocationID As Integer = -1

    Private m_Lot As String = String.Empty

    Private m_ListPrice As Double = 0

    Private m_IsFreeGoods As Boolean = False

    Private m_ExpiryDate As Date = "1/1/1900"

    Private m_ManufacturingDate As Date = "1/1/1900"

    Private m_Remarks As String = String.Empty

    Private m_MarkForDelete As Boolean = False


    Public Property MarkForDelete() As Boolean
        Get
            Return m_MarkForDelete
        End Get
        Set(ByVal value As Boolean)
            m_MarkForDelete = value
        End Set
    End Property

    Public ReadOnly Property BillingOrderDetailID() As Integer
        Get
            Return m_BillingOrderDetailID
        End Get
    End Property

    Public Property BillingOrderID() As Integer
        Get
            Return m_BillingOrderID
        End Get
        Set(ByVal value As Integer)
            m_BillingOrderID = value
        End Set
    End Property

    Public Property ItemID() As String
        Get
            Return m_ItemID
        End Get
        Set(ByVal value As String)
            m_ItemID = value
        End Set
    End Property

    Public Property Quantity() As Decimal
        Get
            Return m_Quantity
        End Get
        Set(ByVal value As Decimal)
            m_Quantity = value
        End Set
    End Property

    Public Property UnitOfMeasureID() As Integer
        Get
            Return m_UnitOfMeasureID
        End Get
        Set(ByVal value As Integer)
            m_UnitOfMeasureID = value
        End Set
    End Property

    Public Property Discount() As String
        Get
            Return m_Discount
        End Get
        Set(ByVal value As String)
            m_Discount = value
        End Set
    End Property

    Public Property VatExclusiveRawDataAmount() As Double
        Get
            Return m_VatExcusiveRawDataAmount
        End Get
        Set(ByVal value As Double)
            m_VatExcusiveRawDataAmount = value
        End Set
    End Property

    Public Property Amount() As Double
        Get
            Return m_Amount
        End Get
        Set(ByVal value As Double)
            m_Amount = value
        End Set
    End Property

    Public Property UnitPrice() As Double
        Get
            Return m_UnitPrice
        End Get
        Set(ByVal value As Double)
            m_UnitPrice = value
        End Set
    End Property

    Public Property DiscountAmount() As Double
        Get
            Return m_DiscountAmount
        End Get
        Set(ByVal value As Double)
            m_DiscountAmount = value
        End Set
    End Property

    Public Property WarehouseID() As Integer
        Get
            Return m_WarehouseID
        End Get
        Set(ByVal value As Integer)
            m_WarehouseID = value
        End Set
    End Property

    Public Property WarehouseLocationID() As Integer
        Get
            Return m_WarehouseLocationID
        End Get
        Set(ByVal value As Integer)
            m_WarehouseLocationID = value
        End Set
    End Property

    Public Property Lot() As String
        Get
            Return m_Lot
        End Get
        Set(ByVal value As String)
            m_Lot = value
        End Set
    End Property

    Public Property ListPrice() As Double
        Get
            Return m_ListPrice
        End Get
        Set(ByVal value As Double)
            m_ListPrice = value
        End Set
    End Property

    Public Property IsFreeGoods() As Boolean
        Get
            Return m_IsFreeGoods
        End Get
        Set(ByVal value As Boolean)
            m_IsFreeGoods = value
        End Set
    End Property

    Public Property ExpiryDate() As Date
        Get
            Return m_ExpiryDate
        End Get
        Set(ByVal value As Date)
            m_ExpiryDate = value
        End Set
    End Property

    Public Property ManufacturingDate() As Date
        Get
            Return m_ManufacturingDate
        End Get
        Set(ByVal value As Date)
            m_ManufacturingDate = value
        End Set
    End Property

    Public Property Remarks() As String
        Get
            Return m_Remarks
        End Get
        Set(ByVal value As String)
            m_Remarks = value
        End Set
    End Property

    Public Function Save() As Boolean
        If SPMSConn2.State = ConnectionState.Closed Or SPMSConn2.State = ConnectionState.Broken Then Connect()
        Try

            If m_MarkForDelete = True Then
                Delete()
                Return True
            End If

            Dim cmd As New SqlCommand("uspBillingOrderDetails", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Save")
            cmd.Parameters.AddWithValue("@BillingOrderDetailID", m_BillingOrderDetailID)
            cmd.Parameters.AddWithValue("@BillingOrderID", m_BillingOrderID)
            cmd.Parameters.AddWithValue("@ItemID", m_ItemID)
            cmd.Parameters.AddWithValue("@Quantity", m_Quantity)
            cmd.Parameters.AddWithValue("@UnitOfMeasureID", m_UnitOfMeasureID)
            cmd.Parameters.AddWithValue("@Discount", m_Discount)
            cmd.Parameters.AddWithValue("@Amount", m_Amount)
            cmd.Parameters.AddWithValue("@VatInclusiveRawDataNetAmount", m_VatExcusiveRawDataAmount)
            cmd.Parameters.AddWithValue("@UnitPrice", m_UnitPrice)
            cmd.Parameters.AddWithValue("@DiscountAmount", m_DiscountAmount)
            cmd.Parameters.AddWithValue("@WarehouseID", m_WarehouseID)
            cmd.Parameters.AddWithValue("@WarehouseLocationID", m_WarehouseLocationID)
            cmd.Parameters.AddWithValue("@Lot", m_Lot)
            cmd.Parameters.AddWithValue("@ListPrice", m_ListPrice)
            cmd.Parameters.AddWithValue("@IsFreeGoods", m_IsFreeGoods)
            cmd.Parameters.AddWithValue("@ExpiryDate", m_ExpiryDate)
            cmd.Parameters.AddWithValue("@ManufacturingDate", m_ManufacturingDate)
            cmd.Parameters.AddWithValue("@Remarks", m_Remarks)
            m_BillingOrderDetailID = cmd.ExecuteScalar()
            Disconnect()
            Return True
        Catch ex As System.Exception
            Disconnect()
            Throw
        End Try
    End Function

    Public Function Delete() As Boolean

        Try
            Connect()
            Dim cmd As New SqlCommand("uspBillingOrderDetails", SPMSOPCI.ConnectionModule.SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Delete")
            cmd.Parameters.AddWithValue("@BillingOrderDetailID", m_BillingOrderDetailID)
            cmd.ExecuteNonQuery()
            Disconnect()
            Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function

    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As BillingOrderDetailsCollection
        Dim col As New BillingOrderDetailsCollection
        For j As Integer = 0 To table.Rows.Count - 1
            Dim m_BillingOrderDetails As New BillingOrderDetails
            Dim row As DataRow = table.Rows(j)
            m_BillingOrderDetails.m_BillingOrderDetailID = row("BillingOrderDetailID")
            m_BillingOrderDetails.m_BillingOrderID = row("BillingOrderID")
            m_BillingOrderDetails.m_ItemID = row("ItemID")
            m_BillingOrderDetails.m_Quantity = row("Quantity")
            m_BillingOrderDetails.m_UnitOfMeasureID = row("UnitOfMeasureID")
            m_BillingOrderDetails.m_Discount = row("Discount")
            m_BillingOrderDetails.m_Amount = row("Amount")
            m_BillingOrderDetails.m_UnitPrice = row("UnitPrice")
            m_BillingOrderDetails.m_DiscountAmount = row("DiscountAmount")
            m_BillingOrderDetails.m_WarehouseID = row("WarehouseID")
            m_BillingOrderDetails.m_WarehouseLocationID = row("WarehouseLocationID")
            m_BillingOrderDetails.m_Lot = row("Lot")
            m_BillingOrderDetails.m_ListPrice = row("ListPrice")
            m_BillingOrderDetails.m_IsFreeGoods = row("IsFreeGoods")
            m_BillingOrderDetails.m_ExpiryDate = row("ExpiryDate")
            m_BillingOrderDetails.m_ManufacturingDate = row("ManufacturingDate")
            m_BillingOrderDetails.m_Remarks = row("Remarks")
            col.Add(m_BillingOrderDetails)
        Next
        Return col
    End Function

    Public Shared Function Filter(ByVal Condition As String) As BillingOrderDetailsCollection
        Return BaseFilter(GetRecords("SELECT * FROM BillingOrderDetails" & IIf(Condition = "", "", " WHERE " & Condition)))
    End Function


    Public Overloads Shared Function Load() As BillingOrderDetailsCollection
        Return Filter("")
    End Function

    Public Shared Function LoadByBillingOrder(ByVal BillingOrderID As Integer) As BillingOrderDetailsCollection
        Return Filter("BillingOrderID = " & BillingOrderID)
    End Function

    Public Overloads Shared Function Load(ByVal BillingOrderDetailID As Integer) As BillingOrderDetails
        Return Filter("BillingOrderDetailID = " & BillingOrderDetailID)(0)
    End Function


End Class

Public Class BillingOrderDetailsCollection

    Inherits List(Of BillingOrderDetails)
End Class
