'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule

Public Class SharingCompany

    Public Const SharingCompanyTableConstant As String = "SharingCompany"

    Private m_Recid As Integer = -1

    Private m_CUTYEAR As String = String.Empty

    Private m_CUTMO As String = String.Empty

    Private m_COMID As String = String.Empty

    Private m_CUSCD As String = String.Empty

    Private m_CUSNAM As String = String.Empty

    Private m_CDACD As String = String.Empty

    Private m_CDANAME As String = String.Empty

    Private m_TERRCD As String = String.Empty

    Private m_STSLSMNCD As String = String.Empty

    Private m_STSLSMNNAME As String = String.Empty

    Private m_ITEMDIVCD As String = String.Empty

    Private m_PERSHR As Decimal = 0.0

    Private m_DELFLAG As Boolean = False

    Private m_IsActive As Boolean = True

    Private m_ConfigTypeCode As String = String.Empty

    Private m_ProductItemGroup As String = String.Empty

    Private m_SharignCom As New SharingCollection




    Public ReadOnly Property Recid() As Integer
        Get
            Return m_Recid
        End Get
    End Property

    Public Property CUTYEAR() As String
        Get
            Return m_CUTYEAR
        End Get
        Set(ByVal value As String)
            m_CUTYEAR = Value
        End Set
    End Property

    Public Property CUTMO() As String
        Get
            Return m_CUTMO
        End Get
        Set(ByVal value As String)
            m_CUTMO = Value
        End Set
    End Property

    Public Property COMID() As String
        Get
            Return m_COMID
        End Get
        Set(ByVal value As String)
            m_COMID = Value
        End Set
    End Property

    Public Property CUSCD() As String
        Get
            Return m_CUSCD
        End Get
        Set(ByVal value As String)
            m_CUSCD = Value
        End Set
    End Property
    Public Property CUSNAM() As String
        Get
            Return m_CUSNAM
        End Get
        Set(ByVal value As String)
            m_CUSNAM = value
        End Set
    End Property
    Public Property CDACD() As String
        Get
            Return m_CDACD
        End Get
        Set(ByVal value As String)
            m_CDACD = value
        End Set
    End Property
    Public Property CDANAME() As String
        Get
            Return m_CDANAME
        End Get
        Set(ByVal value As String)
            m_CDANAME = value
        End Set
    End Property
    Public Property TERRCD() As String
        Get
            Return m_TERRCD
        End Get
        Set(ByVal value As String)
            m_TERRCD = value
        End Set
    End Property
    Public Property STSLSMNCD() As String
        Get
            Return m_STSLSMNCD
        End Get
        Set(ByVal value As String)
            m_STSLSMNCD = value

        End Set
    End Property
    Public Property STSLSMNNAME() As String
        Get
            Return m_STSLSMNNAME
        End Get
        Set(ByVal value As String)
            m_STSLSMNNAME = value
        End Set
    End Property
    Public Property ITEMDIVCD() As String
        Get
            Return m_ITEMDIVCD
        End Get
        Set(ByVal value As String)
            m_ITEMDIVCD = value
        End Set
    End Property
    Public Property ProductItemGroup As String
        Get
            Return m_ProductItemGroup
        End Get
        Set(value As String)
            m_ProductItemGroup = value
        End Set
    End Property
    Public Property PERSHR() As Double
        Get
            Return m_PERSHR
        End Get
        Set(ByVal value As Double)
            m_PERSHR = value
        End Set
    End Property
    Public Property DELFLAG() As Boolean
        Get
            Return m_DELFLAG
        End Get
        Set(ByVal value As Boolean)
            m_DELFLAG = False
        End Set
    End Property
    Public Property IsActive() As Boolean
        Get
            Return m_IsActive
        End Get
        Set(ByVal value As Boolean)
            m_IsActive = True
        End Set
    End Property
    Public Property ConfigTypeCode() As String
        Get
            Return m_ConfigTypeCode
        End Get
        Set(ByVal value As String)
            m_ConfigTypeCode = value
        End Set
    End Property

    Public Function Save() As Boolean
        Connect()
        Try

            Dim cmd As New SqlCommand("uspSharing", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Save")
            cmd.Parameters.AddWithValue("@Recid", m_Recid)
            cmd.Parameters.AddWithValue("@CUTYEAR", m_CUTYEAR)
            cmd.Parameters.AddWithValue("@CUTMO", m_CUTMO)
            cmd.Parameters.AddWithValue("@COMID", m_COMID)
            cmd.Parameters.AddWithValue("@CUSCD", m_CUSCD)
            cmd.Parameters.AddWithValue("@CUSNAM", m_CUSNAM)
            cmd.Parameters.AddWithValue("@CDACD", m_CDACD)
            cmd.Parameters.AddWithValue("@CDANAME", m_CDANAME)
            cmd.Parameters.AddWithValue("@TERRCD", m_TERRCD)
            cmd.Parameters.AddWithValue("@STSLSMNCD", m_STSLSMNCD)
            cmd.Parameters.AddWithValue("@STSLSMNNAME", m_STSLSMNNAME)
            cmd.Parameters.AddWithValue("@ITEMDIVCD", m_ITEMDIVCD)
            cmd.Parameters.AddWithValue("@PERSHR", m_PERSHR)
            cmd.Parameters.AddWithValue("@DELFLAG", m_DELFLAG)
            cmd.Parameters.AddWithValue("@IsActive", m_IsActive)
            cmd.Parameters.AddWithValue("@ConfigtypeCode", m_ConfigTypeCode)
            m_Recid = cmd.ExecuteScalar()
            Disconnect()
            For j As Integer = 0 To m_SharignCom.Count - 1
                m_SharignCom(j).CUTMO = m_CUTMO
                If Not m_SharignCom(j).Save Then
                    Throw New Exception("Error saving ItemCostingDetails Index " & j)
                End If
            Next
            Return True
        Catch ex As System.Exception
            Disconnect()
            Throw
        End Try
    End Function

    Public Function Delete() As Boolean
        Connect()
        Try
            For j As Integer = 0 To m_SharignCom.Count - 1
                If Not m_SharignCom(j).Delete Then
                    Throw New Exception("Error deleting Uploading Index " & j)
                End If
            Next
            Dim cmd As New SqlCommand("uspSharingCompany", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Delete")
            cmd.Parameters.AddWithValue("@Recid", m_Recid)
            cmd.ExecuteNonQuery()
            Disconnect()
            Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function

    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As SharingCompanyCollection
        Dim col As New SharingCompanyCollection
        For j As Integer = 0 To table.Rows.Count - 1
            Dim m_SharingCompany As New SharingCompany
            Dim row As DataRow = table.Rows(j)
            m_SharingCompany.m_Recid = row("Recid")
            m_SharingCompany.m_CUTYEAR = row("CUTYEAR")
            m_SharingCompany.m_CUTMO = row("CUTMO")
            m_SharingCompany.m_COMID = row("COMID")
            m_SharingCompany.m_CUSCD = row("CUSCD")
            m_SharingCompany.m_CUSNAM = row("CUSNAM")
            m_SharingCompany.m_CDACD = row("CDACD")
            m_SharingCompany.m_CDANAME = row("CDANAME")
            m_SharingCompany.m_TERRCD = row("TERRCD")
            m_SharingCompany.m_STSLSMNCD = row("STSLSMNCD")
            m_SharingCompany.m_STSLSMNNAME = row("STSLSMNNAME")
            m_SharingCompany.m_ITEMDIVCD = row("ITEMDIVCD")
            m_SharingCompany.m_ProductItemGroup = row("PITEMGROUP")
            m_SharingCompany.m_PERSHR = row("PERSHR")
            m_SharingCompany.m_DELFLAG = row("DELFLAG")
            m_SharingCompany.m_IsActive = row("IsActive")
            m_SharingCompany.m_ConfigTypeCode = row("ConfigTypeCode")
            col.Add(m_SharingCompany)
        Next
        Return col
    End Function
    Public Shared Function GetSharingCodeForUpload() As String()
        Dim dt As DataTable = GetRecords("SELECT Distinct COMID FROM SharingCompany")
        Dim agent As New List(Of String)
        For m As Integer = 0 To dt.Rows.Count - 1
            agent.Add(dt.Rows(m)("COMID"))
        Next
        Return agent.ToArray
    End Function

    Public Shared Function UploadSharingFromSource(ByVal CUTYEAR As String, ByVal CUTMO As String) As Integer
        Connect()
        Dim id As String = -1
        Dim cmd As New SqlCommand("uspSharingCompany", SPMSConn2)
        cmd.CommandType = CommandType.StoredProcedure
        cmd.Parameters.AddWithValue("@CUTMO", Convert.ToInt16(CUTMO))
        cmd.Parameters.AddWithValue("@CUTYEAR", Convert.ToInt16(CUTYEAR))
        id = cmd.ExecuteScalar
        Disconnect()
        Return id
    End Function
  

    Public Shared Function Filter(ByVal Condition As String) As SharingCompanyCollection
        Return BaseFilter(GetRecords("SELECT * FROM SharingCompany " & IIf(Condition <> "", " WHERE " & Condition, "")))
    End Function

    Public Overloads Shared Function Load() As SharingCompanyCollection
        Return Filter("")
    End Function

    Public Overloads Shared Function Load(ByVal Recid As Integer) As SharingCompany
        Return Filter("Recid = " & Recid)(0)
    End Function
    Public Shared Function LoadBySharing(ByVal Sharing As String) As SharingCompanyCollection
        Return Filter("COMID = '" & HandleSingleQuoteInSql(Sharing) & "' ")
    End Function
    Public Shared Function DeleteExistIfitempriceList(ByVal CompanyCode As String, ByVal Year As String, ByVal Month As String, ByVal ConfigtypeCode As String) As Boolean
        Return ExecuteCommand("DELETE FROM Sharing Where Comid = '" & CompanyCode & "' AND Cutyear = '" & Year & "' AND Cutmo = '" & Month & "' AND Configtypecode = '" & ConfigtypeCode & "'")
    End Function
    Public Shared Function CheckIfItempriceListDataExist(ByVal CompanyCode As String, ByVal year As String, ByVal Month As String, ByVal ConfigtypeCode As String) As Boolean
        Return ExecuteCommand("SELECT * FROM Sharing Where Comid = '" & CompanyCode & "' AND CutYear  = '" & year & "' AND Cutmo = '" & Month & "' AND Configtypecode = '" & ConfigtypeCode & "'")
    End Function
End Class

Public Class SharingCompanyCollection

    Inherits List(Of SharingCompany)
End Class
