'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports SPMSOPCI.ConnectionModule

Public Class Sharing

    Public Const SharingTableConstant As String = "Sharing"

    Private m_Recid As Integer = 0

    Private m_CUTYEAR As String = String.Empty

    Private m_CUTMO As String = String.Empty

    Private m_COMID As String = String.Empty

    Private m_CUSCD As String = String.Empty

    Private m_CUSNAM As String = String.Empty

    Private m_CDACD As String = String.Empty

    Private m_CDANAME As String = String.Empty

    Private m_TERRCD As String = String.Empty

    Private m_STSLSMNCD As String = String.Empty

    Private m_STSLSMNNAME As String = String.Empty

    Private m_ITEMDIVCD As String = String.Empty

    Private m_PERSHR As Decimal = 0.0

    Private m_DELFLAG As Boolean = False

    Private m_IsActive As Boolean = True

    Private m_SharignCom As New SharingCollection

    Public ReadOnly Property Recid() As Integer
        Get
            Return m_Recid
        End Get
    End Property

    Public Property CUTYEAR() As String
        Get
            Return m_CUTYEAR
        End Get
        Set(ByVal value As String)
            m_CUTYEAR = Value
        End Set
    End Property

    Public Property CUTMO() As String
        Get
            Return m_CUTMO
        End Get
        Set(ByVal value As String)
            m_CUTMO = Value
        End Set
    End Property

    Public Property COMID() As String
        Get
            Return m_COMID
        End Get
        Set(ByVal value As String)
            m_COMID = Value
        End Set
    End Property

    Public Property CUSCD() As String
        Get
            Return m_CUSCD
        End Get
        Set(ByVal value As String)
            m_CUSCD = Value
        End Set
    End Property

    Public Property CUSNAM() As String
        Get
            Return m_CUSNAM
        End Get
        Set(ByVal value As String)
            m_CUSNAM = Value
        End Set
    End Property

    Public Property CDACD() As String
        Get
            Return m_CDACD
        End Get
        Set(ByVal value As String)
            m_CDACD = Value
        End Set
    End Property

    Public Property CDANAME() As String
        Get
            Return m_CDANAME
        End Get
        Set(ByVal value As String)
            m_CDANAME = Value
        End Set
    End Property

    Public Property TERRCD() As String
        Get
            Return m_TERRCD
        End Get
        Set(ByVal value As String)
            m_TERRCD = Value
        End Set
    End Property

    Public Property STSLSMNCD() As String
        Get
            Return m_STSLSMNCD
        End Get
        Set(ByVal value As String)
            m_STSLSMNCD = Value
        End Set
    End Property

    Public Property STSLSMNNAME() As String
        Get
            Return m_STSLSMNNAME
        End Get
        Set(ByVal value As String)
            m_STSLSMNNAME = Value
        End Set
    End Property

    Public Property ITEMDIVCD() As String
        Get
            Return m_ITEMDIVCD
        End Get
        Set(ByVal value As String)
            m_ITEMDIVCD = Value
        End Set
    End Property

    Public Property PERSHR() As String
        Get
            Return m_PERSHR
        End Get
        Set(ByVal value As String)
            m_PERSHR = value
        End Set
    End Property

    Public Property DELFLAG() As String
        Get
            Return m_DELFLAG
        End Get
        Set(ByVal value As String)
            m_DELFLAG = False
        End Set
    End Property

    Public Property IsActive() As String
        Get
            Return m_IsActive
        End Get
        Set(ByVal value As String)
            m_IsActive = True
        End Set
    End Property

    Public Function Save() As Boolean
        Connect()
        Try

            Dim cmd As New SqlCommand("uspSharing", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Save")
            cmd.Parameters.AddWithValue("@Recid", m_Recid)
            cmd.Parameters.AddWithValue("@CUTYEAR", m_CUTYEAR)
            cmd.Parameters.AddWithValue("@CUTMO", m_CUTMO)
            cmd.Parameters.AddWithValue("@COMID", m_COMID)
            cmd.Parameters.AddWithValue("@CUSCD", m_CUSCD)
            cmd.Parameters.AddWithValue("@CUSNAM", m_CUSNAM)
            cmd.Parameters.AddWithValue("@CDACD", m_CDACD)
            cmd.Parameters.AddWithValue("@CDANAME", m_CDANAME)
            cmd.Parameters.AddWithValue("@TERRCD", m_TERRCD)
            cmd.Parameters.AddWithValue("@STSLSMNCD", m_STSLSMNCD)
            cmd.Parameters.AddWithValue("@STSLSMNNAME", m_STSLSMNNAME)
            cmd.Parameters.AddWithValue("@ITEMDIVCD", m_ITEMDIVCD)
            cmd.Parameters.AddWithValue("@PERSHR", m_PERSHR)
            cmd.Parameters.AddWithValue("@DELFLAG", m_DELFLAG)
            cmd.Parameters.AddWithValue("@IsActive", m_IsActive)
            m_Recid = cmd.ExecuteScalar()
            For j As Integer = 0 To m_SharignCom.Count - 1
                m_SharignCom(j).CUTMO = m_CUTMO
                If Not m_SharignCom(j).Save Then
                    Throw New Exception("Error saving ItemCostingDetails Index " & j)
                End If
            Next
            Return True
        Catch ex As System.Exception
            Disconnect()
            Throw
        End Try
    End Function

    Public Function Delete() As Boolean
        Connect()
        Try

            Dim cmd As New SqlCommand("uspSharing", SPMSConn2)
            cmd.CommandType = CommandType.StoredProcedure
            cmd.Parameters.AddWithValue("@Action", "Delete")
            cmd.Parameters.AddWithValue("@Recid", m_Recid)
            cmd.ExecuteNonQuery()
            Disconnect()
            Return True
        Catch ex As System.Exception
            Throw
        End Try
    End Function

    Private Shared Function BaseFilter(ByVal table As System.Data.DataTable) As SharingCollection
        Dim col As New SharingCollection
        For j As Integer = 0 To table.Rows.Count - 1
            Dim m_Sharing As New Sharing
            Dim row As DataRow = table.Rows(j)
            m_Sharing.m_Recid = row("Recid")
            m_Sharing.m_CUTYEAR = row("CUTYEAR")
            m_Sharing.m_CUTMO = row("CUTMO")
            m_Sharing.m_COMID = row("COMID")
            m_Sharing.m_CUSCD = row("CUSCD")
            m_Sharing.m_CUSNAM = row("CUSNAM")
            m_Sharing.m_CDACD = row("CDACD")
            m_Sharing.m_CDANAME = row("CDANAME")
            m_Sharing.m_TERRCD = row("TERRCD")
            m_Sharing.m_STSLSMNCD = row("STSLSMNCD")
            m_Sharing.m_STSLSMNNAME = row("STSLSMNNAME")
            m_Sharing.m_ITEMDIVCD = row("ITEMDIVCD")
            m_Sharing.m_PERSHR = row("PERSHR")
            m_Sharing.m_DELFLAG = row("DELFLAG")
            m_Sharing.m_IsActive = row("IsActive")
            col.Add(m_Sharing)
        Next
        Return col
    End Function

    Public Shared Function Filter(ByVal Condition As String) As SharingCollection
        Return BaseFilter(GetRecords("SELECT * FROM Sharing " & IIf(Condition <> "", " WHERE " & Condition, "")))
    End Function

    Public Overloads Shared Function Load() As SharingCollection
        Return Filter("")
    End Function

    Public Overloads Shared Function Load(ByVal Recid As Integer) As Sharing
        Return Filter("Recid = " & Recid)(0)
    End Function
    Public Shared Function LoadBySharing(ByVal SalesAgentCode As String) As SharingCollection
        Return Filter("COMID = '" & HandleSingleQuoteInSql(SalesAgentCode) & "' ")
    End Function
 
End Class
Public Class SharingCollection

    Inherits List(Of Sharing)
End Class

